In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/title_pairs_desc/decorte_master.csv")

In [3]:
df.head()

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id
0,0,Line Cook,- Prepped food for the line and cooked appetiz...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,0
1,1,Line Chef,- Prepared food for the kitchen and created sp...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,1
2,2,Executive Chef,- Promoted from rounds chef to sous chef in 20...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,2
3,3,Banquet Cook 2( Lead Cook),- Attended daily BEO meetings\n- Prepped and f...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,3
4,4,Kitchen Supervisor,- Oversaw the am shift\n- Part of a renovation...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,4

In [6]:
df.tail()

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id
7925,836,Intraday Operations Analyst,Supervised a team responsible for intraday wor...,call centre supervisor,Call centre supervisors oversee call centre em...,http://data.europa.eu/esco/occupation/6aa78e46...,7925
7926,837,Consultant,Supervised operations and project implementati...,business service manager,Business service managers are reponsible for t...,http://data.europa.eu/esco/occupation/3c136897...,7926
7927,838,Workforce Specialist (WFM),Ensured optimum intraday staffing and performa...,contact centre supervisor,Contact centre supervisors oversee and coordin...,http://data.europa.eu/esco/occupation/9d2aae3e...,7927
7928,839,Sr. Workforce Manager,Reduced non-productive agent time by 33% for a...,contact centre manager,Contact centre managers coordinate and plan th...,http://data.europa.eu/esco/occupation/f5166c6b...,7928
7929,840,Workforce Planning Manager,Managed a team of five workforce and Kronos an...,call centre manager,Call centre managers set the objectives of the...,http://data.europa.eu/esco/occupation/dd25a2b0...,7929

In [9]:
df.iloc[7925, 2]

'Supervised a team responsible for intraday workforce management operations. Chaired team meetings for quality work product. Reported daily metrics of help desk performance. Leveraged workforce on an intraday basis and adjusted manpower real-time. Co-created and co-chaired Values Committee and Stream University for workforce development and lower attrition.'

In [4]:
# Calculate text length statistics for raw_description
desc_lengths = df['raw_description'].str.len()

print("Raw Description Length Statistics:")
print(f"Mean: {desc_lengths.mean():.2f}")
print(f"Median: {desc_lengths.median():.2f}")
print(f"Min: {desc_lengths.min()}")
print(f"Max: {desc_lengths.max()}")
print(f"\nPercentiles:")
print(f"25th: {desc_lengths.quantile(0.25):.2f}")
print(f"50th: {desc_lengths.quantile(0.50):.2f}")
print(f"75th: {desc_lengths.quantile(0.75):.2f}")
print(f"90th: {desc_lengths.quantile(0.90):.2f}")
print(f"95th: {desc_lengths.quantile(0.95):.2f}")
print(f"99th: {desc_lengths.quantile(0.99):.2f}")

Raw Description Length Statistics:
Mean: 515.38
Median: 416.00
Min: 13.0
Max: 5043.0

Percentiles:
25th: 267.00
50th: 416.00
75th: 641.00
90th: 950.00
95th: 1233.00
99th: 1978.95

In [5]:
from sentence_transformers import SentenceTransformer

# Load the model
model = SentenceTransformer('ElenaSenger/career-path-representation-mpnet-decorte')

# Get the max sequence length
max_seq_length = model.max_seq_length

print(f"Model: ElenaSenger/career-path-representation-mpnet-decorte")
print(f"Max sequence length: {max_seq_length} tokens")
print(f"\nNote: This is the maximum number of tokens the model can process.")
print(f"Texts longer than this will be truncated.")

Model: ElenaSenger/career-path-representation-mpnet-decorte
Max sequence length: 384 tokens

Note: This is the maximum number of tokens the model can process.
Texts longer than this will be truncated.

In [1]:
import pandas as pd

# Path to the skills master CSV file
skills_path = "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95kix2/results/karrierewege_esco_100k_esco_ground_truth/job_title_skills_master.csv"

# Load the data into a DataFrame
skills_df = pd.read_csv(skills_path)

print("Loaded job_title_skills_master.csv")
print(skills_df.head())

Loaded job_title_skills_master.csv
   original_row_index    job_title              skill  score  \
0                   0  3d modeller       3D texturing    1.0
1                   0  3d modeller        3D lighting    1.0
2                   0  3d modeller  augmented reality    1.0
3                   0  3d modeller  computer graphics    1.0
4                   0  3d modeller         holography    1.0

                                            skillUri
0  http://data.europa.eu/esco/skill/3e7516dc-0f7c...
1  http://data.europa.eu/esco/skill/6e53fd99-b646...
2  http://data.europa.eu/esco/skill/abdc7ac8-151f...
3  http://data.europa.eu/esco/skill/afda6ca0-7aa8...
4  http://data.europa.eu/esco/skill/fcb7ca53-130f...

In [6]:
import json

# Path to the fused scores JSON file
fused_scores_path = "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95kix2/outputs/linear_fusion_sum/best_fused_scores.json"

# Load the JSON data
with open(fused_scores_path, "r") as f:
    fused_scores = json.load(f)

print("Loaded best_fused_scores.json")
print("Keys:", list(fused_scores.keys()))
if len(fused_scores) > 0:
    first_key = list(fused_scores.keys())[0]
    print(f"\nSample for first key '{first_key}':\n", fused_scores[first_key])

Loaded best_fused_scores.json
Keys: ['metadata', 'scores']

Sample for first key 'metadata':
 {'fusion_mode': 'linear', 'aggregate': 'sum', 'top_k': 100, 'n_jobs': 7930, 'best_config_key': 'alpha0.20_T1.00_thres0.40', 'config': {'alpha': 0.2, 'temperature': 1.0, 'threshold': 0.4, 'map_full': 0.10541368526171582}}

In [8]:
len(fused_scores['scores'].keys())

7930

In [56]:
import pandas as pd
df = pd.read_csv('/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/decorte_master.csv')

In [57]:
df.head()

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id
0,0,Line Cook,- Prepped food for the line and cooked appetiz...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,0
1,1,Line Chef,- Prepared food for the kitchen and created sp...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,1
2,2,Executive Chef,- Promoted from rounds chef to sous chef in 20...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,2
3,3,Banquet Cook 2( Lead Cook),- Attended daily BEO meetings\n- Prepped and f...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,3
4,4,Kitchen Supervisor,- Oversaw the am shift\n- Part of a renovation...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,4

In [5]:
df.job_id.describe()

count    7930.00000
mean     3964.50000
std      2289.33815
min         0.00000
25%      1982.25000
50%      3964.50000
75%      5946.75000
max      7929.00000
Name: job_id, dtype: float64

In [9]:
import pickle

# Path to the test scores pickle file
test_scores_path = "/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95kix2/results/cpp/decorte_static/job_titles_desc/scores/test_scores_text.pkl"

# Load the test scores
with open(test_scores_path, "rb") as f:
    test_scores = pickle.load(f)

print("Loaded test_scores_text.pkl")
print("Type:", type(test_scores))
if hasattr(test_scores, "shape"):
    print("Shape:", test_scores.shape)
else:
    try:
        import numpy as np
        arr = np.array(test_scores)
        print("Converted to array, shape:", arr.shape)
    except Exception as e:
        print("Could not determine shape:", e)

Loaded test_scores_text.pkl
Type: <class 'dict'>
Converted to array, shape: ()

In [10]:
test_scores

{'scores': array([[ 0.03698274,  0.0494951 ,  0.05770375, ..., -0.01978263,
          0.17990671,  0.04454451],
        [ 0.08055464,  0.09808064,  0.09533575, ..., -0.00952173,
          0.20232192,  0.0110376 ],
        [ 0.07507903,  0.09368413,  0.0915006 , ..., -0.0133009 ,
          0.1975559 ,  0.0143446 ],
        ...,
        [ 0.2127574 , -0.01866613, -0.09222065, ...,  0.10738701,
         -0.09430698, -0.02769622],
        [ 0.11017329,  0.07102193,  0.00059131, ...,  0.21999092,
         -0.00515523, -0.02480993],
        [ 0.1116991 ,  0.03320939, -0.02913485, ...,  0.20753339,
         -0.02645975, -0.04009726]], shape=(1802, 1022), dtype=float32),
 'target_labels': ['esco role: industrial maintenance supervisor \n description: Industrial maintenance supervisors organise and supervise the activities and maintenance operations of machines, systems and equipment. They ensure inspections are done according to health, safety and environmental standards, and productivity and quality requirements.',
  'esco role: business coach \n description: Business coaches guide employees of a company or other institution in order to improve their personal effectiveness, increase their job satisfaction, and positively impact their career development in the business setting. They do this by leading the coachee (the person who is being coached) to resolution of their challenges by their own means. Business coaches aim to address specific tasks or reach specific goals, as opposed to overall development.',
  'esco role: construction manager \n description: Construction managers are responsible for the planning and coordination of the construction projects. They provide expertise in the design phase of construction projects by facilitating a better estimate of the costs and the functional implications. They participate on bid processes for construction projects and handle subcontractors to deliver the different stages of the construction process from beginning to completion. They strive to enhance the value of the projects both improving efficiency and creating value for customers.',
  'esco role: marketing assistant \n description: Marketing assistants support all the efforts and operations carried out by marketing managers and officers. They prepare reports in relation to the marketing operations needed by other departments, especially account and financial divisions. They ensure that resources needed by the managers to perform their job are in place. \n\xa0',
  'esco role: research engineer \n description: Research engineers combine research skills and knowledge of engineering principles to assist in the development or design of new products and technology. They also improve existing technical processes, machines and systems and create new, innovative technologies. The duties of research engineers depend on the branch of engineering and the industry in which they work. Research engineers generally work in an office or laboratory, analysing processes and conducting experiments.',
  "esco role: mathematics teacher at secondary school \n description: Mathematics teachers at secondary schools provide education to\xa0students, commonly children and young adults, in a\xa0secondary school setting. They are usually subject teachers, specialised and instructing in their own field of study, mathematics. They prepare lesson plans and materials, monitor the students' progress, assist individually when necessary, and evaluate the students' knowledge and performance on the subject of mathematics\xa0through assignments, tests and examinations.",
  'esco role: industrial production manager \n description: Industrial production managers oversee the operations and the resources needed in industrial plants and manufacturing sites for a smooth running of the operations. They prepare the production schedule by combining the requirements of clients with the resources of the production plant. They organise the journey of incoming raw materials or semi finished products in the plant until a final product is delivered by coordinating inventories, warehouses, distribution, and support activities.',
  'esco role: corporate lawyer \n description: Corporate lawyers provide legal consulting services and representation to corporations and organisations. They give advice on matters relating to taxes, legal rights and patents, international trade, trademarks, and legal financial issues arising from operating a business.',
  "esco role: industrial arts vocational teacher \n description: Industrial arts vocational teachers instruct students in their specialised field of study, industrial arts, which is predominantly practical in nature. They provide theoretical instruction in service of the practical skills and techniques the students must subsequently master for an industrial arts-related profession, working with wood and metal, such as carpenter or sheet metal worker. Industrial arts vocational teachers monitor the students' progress, assist individually when necessary, and evaluate their knowledge and performance on the subject of industrial arts through assignments, tests and examinations.",
  'esco role: membership administrator \n description: Membership administrators ensure an effective membership administration, documentation and communication. They support the membership sales process, the current membership enquiries and the renewal processes.',
  'esco role: electromechanical equipment assembler \n description: Electromechanical equipment assemblers read and interpret blueprints, drawings and instructions to assemble or modify electromechanical equipment or devices. They inspect and test the completed units to guarantee good working order and compliance with specifications and standards.',
  'esco role: user interface designer \n description: User interface designers are in charge of designing user interfaces for applications and systems. They perform layout, graphics and dialogues design activities as well as adaptation activities.',
  "esco role: child care social worker \n description: Child care social workers provide social services to children and their families in order to improve their social and psychological functioning. They aim to maximize family's well-being and protect children from abuse and neglect. They assist adoption arrangements and find foster homes where needed.",
  'esco role: clothing product grader \n description: Clothing product graders produce patterns in different sizes (i.e. scaled-up and scaled-down) to reproduce the same wearing apparel in different sizes. They draft patterns by hand or using software following size charts.',
  'esco role: promotion assistant \n description: Promotion assistants provide support in the implementation of programs and promotional efforts in points-of-sale. They research and administer all the information required by managers to decide whether promotional programs are required. If so, they support in getting of materials and resources for the promotional action.',
  "esco role: ticket sales agent \n description: Ticket sales agents provide initial service to customers, sell travel tickets and fit the reservation offer to customers' queries and needs.",
  'esco role: programme manager \n description: Programme managers coordinate and oversee several projects working simultaneously. They ensure workability and compatibility among projects ensuring that overall, each one of the projects under the management of project managers, turn out profitable and leveraging one to the other.',
  "esco role: further education principal \n description: Further education principals manage the day-to-day activities of a post-secondary education institute, such as technical institutes and other post-secondary schools. Further education principals make decisions concerning admissions and are responsible for meeting curriculum standards, which facilitate academic development for the students. They manage staff, the school's budget and programmes and oversee the communication between departments. They also ensure the school meets the national education requirements set by law.",
  'esco role: online sales channel manager \n description: Online sales channel managers define the sales programme for e-commerce such as goods sold via e-mail, internet and social media. They also assist in planning the online sales strategy and identifying marketing opportunities. Online sales channel managers also analyse competitor sites, review the site performance and analytics.',
  'esco role: maintenance and repair engineer \n description: Maintenance and repair engineers focus on the optimization of equipment, procedures, machineries and infrastructure. They ensure their maximum availability at minimum costs.',
  'esco role: social work supervisor \n description: Social work supervisors manage social work cases by investigating alleged neglect or abuse cases. They make family dynamics assessment and provide assistance to sick people or with emotional or mental disorders. They train, assist, advise, evaluate and assign work to subordinate social workers making sure that all work is done according to the established policies, laws, procedures and priorities.',
  'esco role: specialist biomedical scientist \n description: Specialist biomedical scientists lead a department or specialist area, undertaking clinical research projects and working as a diagnostic partner within the health care team (investigating and diagnosing patient illnesses like, cancer, diabetes, haematological disorders and coagulation, in the areas of molecular biology or genomics, among others) using several methods, digital tools, and bioinformatics.',
  'esco role: travel consultant \n description: Travel consultants provide customised information and\xa0consultation on travel\xa0offers, make reservations and sell travel services together with other related services.',
  'esco role: hotel concierge \n description: Hotel concierges provide information to customers, assist guests with various tasks such as making restaurant reservations, recommending entertainment highlights, booking transportation (limousines, airplanes, boats, etc.) and other services, procurement of tickets to special events, and assisting with various travel arrangements and tours of local attractions.',
  'esco role: scientific laboratory technician \n description: Scientific laboratory technicians carry out laboratory-based research, analysis and testing and support life science professionals. They sample, test, measure, research and analyse in areas such as biology, biotechnology, environmental science, forensic science and pharmacology. Scientific laboratory technicians also observe and monitor laboratory activities, record test sequences and analyse the results.',
  'esco role: ict system integration consultant \n description: ICT system integration consultants advise on bringing together different systems to interoperate within an organisation for enabling data sharing and reducing redundancy.\n',
  "esco role: special educational needs teacher \n description: Special educational needs teachers work with and teach children, young people, and adults with an intellectual or physical disability. They use a range of specialised concepts, strategies and tools to optimise learners' communication, mobility, autonomy, and social integration. They select teaching methods and support resources to enable individual learners to maximise their potential for independent living.",
  'esco role: pastry maker \n description: Pastry makers prepare and bake cakes, cookies, croissants, pies and alike\xa0products according to recipes. \n',
  'esco role: motor vehicle upholsterer \n description: Motor vehicle upholsterers create manufacturing templates, manufacture and assemble interior components for cars, buses, trucks etc. They use power tools, hand tools and shop equipment to prepare and fasten materials. They also inspect incoming materials and prepare the vehicle interior for trim items.',
  'esco role: aircraft assembly supervisor \n description: Aircraft assembly supervisors coordinate the employees involved in aircraft manufacturing and schedule their activities. They prepare production reports and recommend measures to reduce the cost and improve productivity such as hiring, ordering new equipment and implementing new production methods. They train employees in company policies, job duties and safety measures. They oversee the supplies and communicate with other departments to avoid unnecessary interruptions of the production process.',
  'esco role: aircraft maintenance technician \n description: Aircraft maintenance technicians perform preventive maintenance to aircrafts, aircraft components, engines and assemblies, such as airframes and hydraulic and pneumatic systems. They perform inspections following strict protocols and aviation laws.',
  'esco role: library assistant \n description: Library assistants assist the librarian in the day-to-day activities of the library. They help clients find the materials they need, check out library materials and restock the shelves.\xa0',
  'esco role: asset manager \n description: Asset managers invest the money of a client into financial assets, through vehicles such as investment funds or management of individual clients’ portfolios. This includes the management of the financial assets, within a given investment policy and risk framework, the provision of information, and the assessment and monitoring of risks.',
  'esco role: community social worker \n description: Community social workers help people in disadvantage or excluded from society to change their situation and handle their integration problems. They work with communities focusing on specific groups. Community social workers liaise closely with social workers, schools, local authorities and probation officers representing people before policy makers at local and national level.',
  'esco role: conveyance clerk \n description: Conveyance clerks provide services for the legal transference of legal titles and properties from one party to another. They exchange the necessary contracts and ensure all properties, titles and rights are transfered.',
  'esco role: microsystem engineer \n description: Microsystem engineers research, design, develop, and supervise the production of microelectromechanical systems (MEMS), which can be integrated in mechanical, optical, acoustic, and electronic products.',
  "esco role: product assembly inspector \n description: Product assembly inspectors evaluate products for compliance with specifications and defects in-line with clients' requirements and organisational policies. They use measuring and testing equipment to ensure conformity to engineering and manufacturing specifications, quality, and safety standards and regulations.\xa0They also provide detailed inspection documentation and recommend action where problems are discovered.",
  'esco role: industrial designer \n description: Industrial designers work out ideas and develop them into designs and concepts for a wide variety of manufactured products. They integrate creativity, aesthetics, production feasibility, and market relevance in the design of new products.',
  'esco role: social counsellor \n description: Social counsellors provide support and guidance to individuals in the social work area, to help them solve specific problems in their personal life. It involves addressing personal and relationship issues, dealing with inner conflicts, crisis moments such as depression and addiction, in an attempt to empower individuals to achieve change and improve their life quality.',
  'esco role: professional athlete \n description: Professional athletes compete in sports and athletic events. They train on a regular basis and exercise with professional coaches and trainers. ',
  'esco role: accountant \n description: Accountants review and analyse financial statements, budgets, financial reports, and business plans in order to check for irregularities resulting from error or fraud, and provide their clients with financial advice in matters such as financial forecasting and risk analysis. They may audit financial data, resolve insolvency cases, prepare tax returns and provide other tax-related advice in reference to current legislation.',
  'esco role: medical goods shop manager \n description: Medical goods shop managers are responsible for activities and staff in specialised shops. \u200bThey manage employees, monitor the sales of the store, manage budgets and order supplies when a product is out of supply and perform administrative duties if required.',
  'esco role: higher education lecturer \n description: Higher education lecturers instruct students who have obtained an upper secondary education diploma in their own specialised field of study, which is predominantly academic in nature. They may have job titles such as senior lecturer or professor. They work with their teaching and research assistants for the preparation of lectures and exams, for grading papers and exams, for leading laboratory practices, and for leading review and feedback sessions for the students. They also conduct academic research in their respective field, publish their findings and liaise with their academic colleagues.',
  'esco role: bakery specialised seller \n description: Bakery specialised sellers\xa0sell bread and cakes in specialised shops, post-processing the products if required.',
  'esco role: artistic painter \n description: Artistic painters create paintings in oil or water colours or pastel, miniatures, collages, and drawings executed directly by the artist and/or entirely under their control .',
  'esco role: paramedic in emergency responses \n description: Paramedics in emergency responses provide emergency care to sick, injured, and vulnerable persons in emergency medical situations, before and during transport to a medical facility. They implement and oversee the transfer of the patient in connection with transport. They provide assistance in acute situations, implement life-saving emergency measures, and monitor the performance of the transportation process.\xa0As allowed by national law they may also provide oxygen, certain drugs, the puncture of peripheral veins and infusion of crystalloid solutions and perform endotracheal intubation if needed for the immediate prevention of threats for the life or health of an emergency patient.',
  'esco role: sales support assistant \n description: Sales support assistants perform a variety of general sales support tasks, such as supporting the development of sales plans, managing clerical activities of sales efforts, verifying client invoices and other accounting documents or records, compiling data, and preparing reports for other company departments.',
  "esco role: agricultural technician \n description: Agricultural technicians collect and conduct experiments and tests on agriculture and aquaculture specimens. They provide support to scientists and farmers and also analyse and report on conditions in the collected specimens' environments.",
  'esco role: environmental protection manager \n description: Environmental protection managers provide advice on the development of environmental policies to governmental and official institutions. They analyse possible threats for the well being of the people and the environment in a region and manage campaigns aimed at tackling problems such as waste collection, landfills, and preservation of green areas.',

In [1]:
# inv

import pandas as pd
df = pd.read_csv('/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/decorte_master.csv')

In [1]:
from datasets import load_dataset

dataset = load_dataset("jensjorisdecorte/anonymous-working-histories")

In [2]:
def replace_esco_titles(example, i):
    """
    Replaces specific ESCO job titles with alternative titles for consistency.

    Args:
        example (dict): A dictionary representing a dataset row.
        i (int): The index of the ESCO title column.

    Returns:
        dict: Updated dictionary with the replaced ESCO title and URI.
    """
    replacements_title = {
        'ICT security engineer': 'cyber incident responder',
        'ict security engineer': 'cyber incident responder',
        'care at home worker': 'care home worker',
        'residential care home worker': 'care home worker',
        'ICT security manager': 'cybersecurity risk manager',
        'ict security manager': 'cybersecurity risk manager',
        'care at home worker': 'care home worker',
        'handyman': 'handyperson',
        'corporate banking manager': 'corporate banking adviser',
    }

    original_title = example[f'ESCO_title_{i}']
    if not pd.isna(original_title):
        processed_title = original_title.strip().lower()
        final_title = replacements_title.get(processed_title, processed_title)
    else:
        final_title = original_title

    example[f'ESCO_title_{i}'] = final_title

    replacements_uri = {
        'http://data.europa.eu/esco/occupation/81309031-dad2-4a7a-bde6-7f6e518f89ff': 
        'http://data.europa.eu/esco/occupation/f4525ed8-54eb-4a3b-90db-55cc01b0d9fd'
    }
    
    example[f'ESCO_uri_{i}'] = replacements_uri.get(example[f'ESCO_uri_{i}'], example[f'ESCO_uri_{i}'])
    
    return example

In [3]:
import pandas as pd
df_occ = pd.read_csv(r'../data/esco_datasets/occupations_en.csv')

In [4]:
df_skill_rel = pd.read_csv(r'../data/esco_datasets/occupationSkillRelations_en.csv')

In [ ]:
df_occ['iscoGroup_1'] = df_occ.iscoGroup.astype(str).apply(lambda x: x[:1]).astype(int)
df_occ['iscoGroup_2'] = df_occ.iscoGroup.astype(str).apply(lambda x: x[:2]).astype(int)
df_occ['iscoGroup_3'] = df_occ.iscoGroup.astype(str).apply(lambda x: x[:3]).astype(int)
df_occ['iscoGroup_4'] = df_occ.iscoGroup.astype(str).apply(lambda x: x[:4]).astype(int)

In [26]:
df_occ['iscoGroup_1'] = df_occ['code'].astype(str).str[0]
df_occ['iscoGroup_2'] = df_occ['code'].astype(str).str[:2]
df_occ['iscoGroup_3'] = df_occ['code'].astype(str).str[:3]
df_occ['iscoGroup_4'] = df_occ['code'].astype(str).str[:4]

In [27]:
df_occ.merge(df_skill_rel, left_on='conceptUri', right_on='occupationUri', how='inner').groupby(
    'iscoGroup_2'
).skillUri.nunique().describe()

count      42.000000
mean      954.119048
std       832.530061
min        56.000000
25%       351.750000
50%       705.000000
75%      1469.750000
max      3596.000000
Name: skillUri, dtype: float64

In [28]:
df_occ.merge(df_skill_rel, left_on='conceptUri', right_on='occupationUri', how='inner').groupby(
    'iscoGroup_3'
).skillUri.nunique().describe()

count     125.000000
mean      400.336000
std       339.386803
min        16.000000
25%       184.000000
50%       320.000000
75%       519.000000
max      2179.000000
Name: skillUri, dtype: float64

In [29]:
df_occ.merge(df_skill_rel, left_on='conceptUri', right_on='occupationUri', how='inner').groupby(
    'iscoGroup_1'
).skillUri.nunique().describe()

count       9.0000
mean     3325.0000
std      2319.4003
min       755.0000
25%      1361.0000
50%      3116.0000
75%      3708.0000
max      7549.0000
Name: skillUri, dtype: float64

In [4]:
df_occ.iscoGroup.nunique()

426

In [5]:
df_occ[df_occ.preferredLabel.str.lower() == "care home worker"]

,conceptType,conceptUri,iscoGroup,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,regulatedProfessionNote,scopeNote,definition,inScheme,description,code
2899,Occupation,http://data.europa.eu/esco/occupation/f4525ed8...,3412,care home worker,community home care worker\nhome care assistan...,NaN,released,2022-12-22T15:04:36.328Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Care home workers provide domiciliary services...,3412.4.2

In [6]:
df_occ[df_occ.conceptUri.str.lower() == "http://data.europa.eu/esco/occupation/f4525ed8-54eb-4a3b-90db-55cc01b0d9fd"]

,conceptType,conceptUri,iscoGroup,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,regulatedProfessionNote,scopeNote,definition,inScheme,description,code
2899,Occupation,http://data.europa.eu/esco/occupation/f4525ed8...,3412,care home worker,community home care worker\nhome care assistan...,NaN,released,2022-12-22T15:04:36.328Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Care home workers provide domiciliary services...,3412.4.2

In [7]:
df_occ[df_occ.preferredLabel.str.lower() == "care at home worker"]

Empty DataFrame
Columns: [conceptType, conceptUri, iscoGroup, preferredLabel, altLabels, hiddenLabels, status, modifiedDate, regulatedProfessionNote, scopeNote, definition, inScheme, description, code]
Index: []

In [4]:
# Apply replacements to all columns in the dataset beginning with ESCO_title
for i in range(16):
    dataset['train'] = dataset['train'].map(lambda example: replace_esco_titles(example, i))
    dataset['validation'] = dataset['validation'].map(lambda example: replace_esco_titles(example, i))
    dataset['test'] = dataset['test'].map(lambda example: replace_esco_titles(example, i))

In [8]:
dataset['train']

Dataset({
    features: ['identifier', 'industry', 'number_of_experiences', 'uuid_0', 'title_0', 'description_0', 'start_0', 'end_0', 'ESCO_uri_0', 'ESCO_title_0', 'uuid_1', 'title_1', 'description_1', 'start_1', 'end_1', 'ESCO_uri_1', 'ESCO_title_1', 'uuid_2', 'title_2', 'description_2', 'start_2', 'end_2', 'ESCO_uri_2', 'ESCO_title_2', 'uuid_3', 'title_3', 'description_3', 'start_3', 'end_3', 'ESCO_uri_3', 'ESCO_title_3', 'uuid_4', 'title_4', 'description_4', 'start_4', 'end_4', 'ESCO_uri_4', 'ESCO_title_4', 'uuid_5', 'title_5', 'description_5', 'start_5', 'end_5', 'ESCO_uri_5', 'ESCO_title_5', 'uuid_6', 'title_6', 'description_6', 'start_6', 'end_6', 'ESCO_uri_6', 'ESCO_title_6', 'uuid_7', 'title_7', 'description_7', 'start_7', 'end_7', 'ESCO_uri_7', 'ESCO_title_7', 'uuid_8', 'title_8', 'description_8', 'start_8', 'end_8', 'ESCO_uri_8', 'ESCO_title_8', 'uuid_9', 'title_9', 'description_9', 'start_9', 'end_9', 'ESCO_uri_9', 'ESCO_title_9', 'uuid_10', 'title_10', 'description_10', 'start_10', 'end_10', 'ESCO_uri_10', 'ESCO_title_10', 'uuid_11', 'title_11', 'description_11', 'start_11', 'end_11', 'ESCO_uri_11', 'ESCO_title_11', 'uuid_12', 'title_12', 'description_12', 'start_12', 'end_12', 'ESCO_uri_12', 'ESCO_title_12', 'uuid_13', 'title_13', 'description_13', 'start_13', 'end_13', 'ESCO_uri_13', 'ESCO_title_13', 'uuid_14', 'title_14', 'description_14', 'start_14', 'end_14', 'ESCO_uri_14', 'ESCO_title_14', 'uuid_15', 'title_15', 'description_15', 'start_15', 'end_15', 'ESCO_uri_15', 'ESCO_title_15', 'uuid_16', 'title_16', 'description_16', 'start_16', 'end_16', 'ESCO_uri_16', 'ESCO_title_16'],
    num_rows: 1720
})

In [9]:
# Extract all title_k, description_k pairs from the training dataset
all_title_description_pairs = []

for example in dataset['train']:
    num_experiences = example['number_of_experiences']
    for k in range(num_experiences):
        title = example.get(f'title_{k}')
        description = example.get(f'description_{k}')
        esco = example.get(f'ESCO_uri_{k}')
        split = 'train'
        all_title_description_pairs.append([title, description, esco, split])

print(f"Total title-description pairs extracted: {len(all_title_description_pairs)}")
print("\nFirst 5 pairs:")
for i, l in enumerate(all_title_description_pairs[:5]):
    print(f"{i+1}. Title: {l[0]}")
    print(f"   Description: {l[1][:100]}...")
    print(f"   ESCO ID: {l[2][:100]}...")
    print()

Total title-description pairs extracted: 7912

First 5 pairs:
1. Title: Line Cook
   Description: - Prepped food for the line and cooked appetizers, soups, sandwiches, and fried foods
- Detail clean...
   ESCO ID: http://data.europa.eu/esco/occupation/90f75f67-495d-49fa-ab57-2f320e251d7e...

2. Title: Line Cook
   Description: - Prepared food for the line and cooked a variety of dishes
- Created daily specials and closed the ...
   ESCO ID: http://data.europa.eu/esco/occupation/90f75f67-495d-49fa-ab57-2f320e251d7e...

3. Title: Line Chef
   Description: - Prepared food for the kitchen and created specials for the dinner and lunch menu
- Cooked food for...
   ESCO ID: http://data.europa.eu/esco/occupation/01484951-15e6-4b88-a20f-1201868d36a0...

4. Title: Executive Chef
   Description: - Promoted from rounds chef to sous chef in 2009, and then to executive chef in 2011
- Implemented f...
   ESCO ID: http://data.europa.eu/esco/occupation/01484951-15e6-4b88-a20f-1201868d36a0...

5. Title: Banquet Cook 2( Lead Cook)
   Description: - Attended daily BEO meetings
- Prepped and fired functions for upwards of 1500 guests
- Prepared ta...
   ESCO ID: http://data.europa.eu/esco/occupation/90f75f67-495d-49fa-ab57-2f320e251d7e...

In [10]:
for example in dataset['validation']:
    num_experiences = example['number_of_experiences']
    for k in range(num_experiences):
        title = example.get(f'title_{k}')
        description = example.get(f'description_{k}')
        esco = example.get(f'ESCO_uri_{k}')
        split='val'
        all_title_description_pairs.append([title, description, esco, split])

In [11]:
for example in dataset['test']:
    num_experiences = example['number_of_experiences']
    for k in range(num_experiences):
        title = example.get(f'title_{k}')
        description = example.get(f'description_{k}')
        esco = example.get(f'ESCO_uri_{k}')
        split='test'
        all_title_description_pairs.append([title, description, esco,split])

In [12]:
len(all_title_description_pairs)

9919

In [13]:
all_title_description_pairs[0]

['Line Cook',
 '- Prepped food for the line and cooked appetizers, soups, sandwiches, and fried foods\n- Detail cleaned the kitchen\n- Developed strong communication skills in a fast-paced kitchen environment',
 'http://data.europa.eu/esco/occupation/90f75f67-495d-49fa-ab57-2f320e251d7e',
 'train']

In [14]:
# Get unique pairs only, filtering out NaN descriptions
unique_pairs = set()
for title, description, esco_id, split in all_title_description_pairs:
    if pd.notna(description):  # Filter out NaN descriptions
        unique_pairs.add((title, description, esco_id, split))
    else:
        print('hey')
        description = 'na'
        unique_pairs.add((title, description, esco_id, split))

print(f"Total unique title-description-esco pairs (excluding NaN descriptions): {len(unique_pairs)}")

hey
hey
hey
hey
hey
hey
hey
hey
Total unique title-description-esco pairs (excluding NaN descriptions): 9885

In [15]:
# Get items where description is 'na'
na_items = [item for item in unique_pairs if item[1] == 'na']
print(f"Number of items with 'na' description: {len(na_items)}")
na_items[:5]  # Show first 5 items

Number of items with 'na' description: 8

[('Key Hourly Manager',
  'na',
  'http://data.europa.eu/esco/occupation/b7744a45-a4ce-4037-b679-3d2377e17f31',
  'train'),
 ('Delivery Lead',
  'na',
  'http://data.europa.eu/esco/occupation/0c408028-c48f-4df8-ba5d-c3d3be15f5a2',
  'train'),
 ('Regional Training Coordinator and Residential Representative',
  'na',
  'http://data.europa.eu/esco/occupation/a14e96a7-6c4d-4d69-8c6f-7ccadf77bac5',
  'val'),
 ('Math Teacher',
  'na',
  'http://data.europa.eu/esco/occupation/f0e1cc13-48e0-4995-8699-ee43467bce0d',
  'train'),
 ('Assistant Supervisor/Head Bartender',
  'na',
  'http://data.europa.eu/esco/occupation/2f5e38a0-6578-4665-bdbd-e2ab505be140',
  'train')]

In [16]:
unique_pairs

{('Manager, Partner Marketing',
  'Directed partner relations and partner marketing during a hyper-growth period and led cross-divisional teams to onboard strategic partnerships with major media companies such as the National Football League, CBS Sportsline, ABC News, Bloomberg L.P., NBC, Reuters, Web M.D., and Business Week. Developed customized marketing campaigns each month for national media partners resulting in significant customer acquisition. Managed an $18M annual partner marketing budget and a staff of six.',
  'http://data.europa.eu/esco/occupation/6fcf4638-e7c7-4978-9302-9a7b63a3d57c',
  'train'),
 ('Merchandiser, Sales',
  'Worked for Southern Wine & Spirits, a family owned sales and distribution organization. Built relationships with store owners, strategically placed merchandising and marketing materials in stores, and discussed future merchandising opportunities with management. Served as a point of contact for sales reps and assisted them in the field. Organized the warehouse and distributed POS, samples, and other materials to appropriate divisions. Notable accomplishments include building strong relationships with key accounts and booking strategic displays.',
  'http://data.europa.eu/esco/occupation/f1fcad3b-fdf0-444a-81b0-e50e96f8966a',
  'train'),
 ('Digital Merchandising Analyst',
  'Report on sales trends and observations to influence merchandising decisions. Apply search term reporting and SEO ranking results to improve overall website experience through navigation, category levels, and product detail pages (PDPs). Manage seasonal campaigns and ensure they are executed across email, social, affiliate, indirect retailers, and verabradley.com. Executes all omni-channel promotions on verabradley.com. Manages the Digital Product Content Coordinator to oversee all onsite search, SEO execution, navigation, product attributes, and search reporting.',
  'http://data.europa.eu/esco/occupation/1dd7c3cb-2d58-4dad-ae15-c9081174ab7e',
  'val'),
 ('Property Accountant',
  'Assisted the GM in financial forecasts and budgeting, managed tenant billing and reconciliations, oversaw AP function, and dealt with collections and legal matters.',
  'http://data.europa.eu/esco/occupation/0f5b4653-50b2-413a-826d-39d447480c21',
  'train'),
 ('Electrical Power Production Apprentice',
  'Installed, operated, and maintained 37 permanently installed/46 mobile generators, including a 2.8 Mega Watt power plant. Provided comprehensive customer training of emergency generator operations and automatic transfer panels (ATP).',
  'http://data.europa.eu/esco/occupation/72381086-cb6e-455e-a40b-ccb26550aab6',
  'train'),
 ('Customer Service Representative',
  "Answered customer questions and took orders. Assisted customers with finding solutions to their complaints, concerns, and inquiries. Recommended, selected, and helped locate merchandise based on customer needs and desires. Collaborated with customer service team members to give exceptional service throughout the entire shopping and purchasing experience. Built customer confidence by actively listening to their concerns and giving appropriate feedback. Extended customer subscriptions, offering discounts and promotions to ensure high customer retention rates. Confirmed that appropriate changes were made to resolve customers' problems.",
  'http://data.europa.eu/esco/occupation/13d1b2b4-99dd-44da-9734-c9f74bae18f7',
  'val'),
 ('Lead Aerospace Assembler',
  'Trained and led a team of six assemblers to quickly and efficiently build landing gear beams. Ensured all equipment was properly installed and working correctly. Planned work and determined appropriate tools and equipment needed for the workday. Processed work orders and prioritized jobs. Communicated with prior shift to assess work needs for the day.',
  'http://data.europa.eu/esco/occupation/96e139de-0756-45ad-b512-f7c2109a72b1',
  'test'),
 ('Business Enterprise Risk Manager',
  "- Supervised underwriting and business-to-business enterprise risk management to protect the organization from potential risks.\n- Managed 265 satellite offices within the state of Ohio and Kentucky and 8 auditors.\n- Managed information associated with the organization's operations from internal sources.\n- Provided local, state, and federal crime authorities with evidence-based information for client embezzlement and white-collar crime cases.\n- Conducted forecasts to predict the cost-benefit analysis and the impact on net worth/earnings for short-term, mid-term, and long-term scopes.",
  'http://data.europa.eu/esco/occupation/b09acdda-6680-49d1-a411-129610ee3bc0',
  'train'),
 ('CAD Operator/Designer',
  'Worked as a CAD Operator/Designer for a fast-paced MEP firm in New York City. Collaborated closely with Senior Engineers, Architects, and Interior Designers. Worked on various projects including electrical (Power & Lighting), plumbing, sprinklers, and some HVAC. Assisted in multiple areas as needed.',
  'http://data.europa.eu/esco/occupation/62979364-6fac-41f2-87ca-202bca19a6ab',
  'train'),
 ('Assistant Project Manager',
  'Mentored and guided associates in approaches designed to exceed expectations of customers and members. Adapted quickly to changing and competing project demands. Adjusted project plans to account for dynamic targets, staffing changes, and operational specifications. Supported senior managers and department leaders by completing projects and problem resolution under tight budgets and schedule demands. Managed cost projections, prepared budgets and cost reports. Delivered a high level of service to clients to both maintain and extend the relationship for future business opportunities. Closely collaborated with project members to identify and quickly address problems. Reviewed and assisted in accurate exposure projections and actively worked to reduce/eliminate these exposures. Managed upwards of 20 trades at different times during the current project. Managed and completed cost reporting, additional sub management, PE management, monthly progress package, schedule updates, etc. during transition periods of two separate project managers leaving the current project.',
  'http://data.europa.eu/esco/occupation/5ccb2c34-e860-43a5-9869-342487518115',
  'train'),
 ('Systems Engineer Associate',
  'Organized weekly seminars, delivered training, and maintained technical library. Researched and recommended products for Closed Caption video content support. Assisted with candidate recruitment, reviewed resumes, and managed employee information and human resource paperwork.',
  'http://data.europa.eu/esco/occupation/9581c837-fee7-4068-9618-1116fd93d723',
  'train'),
 ('Sales Representative',
  'Gathered information from clients to create solutions that achieved business needs and desires. Increased profitability and revenue by generating $2000 in sales. Networked with customers to increase referrals and boosted new client sales by 13%. Expanded client bases by offering exceptional customer service and telecommunication skills. Drove phone and cable sales through development of successful promotional strategies and product placement. Acquired new customers and identified unique needs to deliver relevant products. Brought motivation and energy to sales floor, creating positive and fun atmosphere. Met with store managers to discuss product needs, accomplish sales goals and facilitate sales growth. Fostered relationships with customers to expand customer base and enhance loyalty and retention. Cultivated impactful relationships with customers and drove business development by delivering product knowledge. Set up and activated customer accounts to maintain QA satisfaction levels.',
  'http://data.europa.eu/esco/occupation/14031d4a-6e99-442f-b4fe-18262b6432b2',
  'train'),
 ('Senior Staff Accountant',
  "Play a significant role in month-end close activities including preparation of production reports, journal entries, and account reconciliations. Analyze financial transactions and assist in the preparation of balance sheets, P&L's, and other financial reports. Ensure accurate coding of transactions and maintain financial reporting integrity. Review & analyze monthly product cost and budget vs. actual reports. Manage Construction in Process Accounts, fixed assets, depreciation, additions, transfers, & dispositions of fixed and intangible assets. Conduct annual physical inventory for fixed assets. Compose quarterly consolidated financial statements. Generate intercompany foreign currency financial statements. Reconcile physical inventory. Calculate year-end raw materials inventory. Compile analysis of corporate financial data for internal reports. Assist with interim & annual audit. Provide analysis and support for ad hoc requests, projects, and other duties.",
  'http://data.europa.eu/esco/occupation/eda0d957-3c3c-4139-b89a-a18bc9e18897',
  'train'),
 ('EcoPRT Research Assistant',
  'Involved in the design and development of an economical, automated transit system. Focus was on the hands-on design and development of a small manned autonomous vehicle. Worked on understanding the impact of weight on cost and performance and incorporated automated control. Assisted with research at www.ecoprt.com.',
  'http://data.europa.eu/esco/occupation/551a6797-3ca9-41fc-9dca-9a982a8fd8a6',
  'train'),
 ('Senior Accountant',
  'Responsible for auditing health insurance billing for school districts in Texas, monitoring delinquent accounts, preparing analysis reports, reconciling accounts, assisting with state regulations, resolving billing issues, and compiling financial reports.',
  'http://data.europa.eu/esco/occupation/eda0d957-3c3c-4139-b89a-a18bc9e18897',
  'train'),
 ('Senior Account Manager',
  'Developed custom public and media relations strategy for a variety of clients integrating PR, marketing, and social media for maximum impact. Wrote, designed, edited, and distributed press releases and media pitches for clients. Provided updates, served on committees, and interacted with clients to advise and customize public relation strategy and tactics to achieve goals. Coordinated, managed, and executed public relations events; tracked media activity; and problem-solved for public relations and crisis issues. Served as liaison and representative to media and community. Managed website content for both Baker PR and clients. Clients included Lord & Taylor, National Center for Adaptive Neurotechnology, Complexions Spa, The Port of Coeymans, Creatacor, and more.',
  'http://data.europa.eu/esco/occupation/6cc19251-763b-4de1-b4f7-526c9ff732d2',
  'train'),
 ('Oracle Database Administrator',
  'Prepared technical architecture proposals for enhancements and migrated an existing standalone database to RAC database. Provided senior technical support to Developers and troubleshot performance issues and maintained high availability and security of databases. Analyzed and tuned the Database to identify potential database bottle necks such as response delay, locking contention, wait event using tools like STATSPACK, EXPLAIN PLAN, and TKPROF. Collaborated and worked together with development and operations staff and resolved problems quickly and efficiently. Maintained Physical, Logical, Active standby databases supported by Data guard on Oracle 11g, and 10g RAC servers for the purpose of disaster recovery procedures. Installed, configured, deployed and monitored different databases and application servers using Oracle OEM 12c Grid Control. Worked efficiently in Database administration activities such as User management, Space management, Monitoring, Creating Database, Managing Oracle Instance and Database security and Materialized views. Maintained and administered high availability solutions such as Real Application Cluster (RAC) in Oracle 11gR2 Grid and 10g on ASM file system. Planned and applied PSU/CPU patches and upgraded multiple databases from 10g to 11g. Replicated data in real time using oracle Golden Gate. Increased data security; implemented TDE and database auditing and created threshold on database metrics and set alert for a more stronger security. Maintained Active Data guard, creating both Logical and Physical Standby databases for data disaster recovery solutions. Worked on 24/7 environments, supported, monitored, managed and troubleshot database related issues over 300 oracle 10g, 11g and 12c databases with sizes from 300G to 2TB. Implemented backup strategies used RMAN for incremental/full backup and Datapump to backup logical components.',
  'http://data.europa.eu/esco/occupation/8c57af09-719c-42b3-be40-6ed4946236cc',
  'train'),
 ('Executive Chef',
  "Managed kitchen and stewarding staff team of 67 and assigned various stages of food production and event management. Designed, managed and created menus for 3 restaurants (offshore 9, Boardwalk and newly opened Henry's), 2 pool pantries and 1 market (Riptide and Surf Hero). Managed, designed menus and cooked for over 51,000 square feet of meeting space. Maintained labor at under 11% to promote long-term business profitability. Purchased ingredients and managed inventory from a variety of vendors which allowed for a hotel wide food costs of 26%. Worked closely on a daily basis with sales and catering to create dynamic cost effective food selections for small banquets and large events for up to 1000 people. Experimented new dish creations by incorporating customer recommendations and feedback. Created recipes, incorporating various techniques, to build flavor and unique visual appeal. Adjusted seasonal plans to source local ingredients and aligned special dishes to complement area events. Worked with vendors to locate optimal recipe ingredients at cost-effective rates. Utilized local, fresh food products to support local economies and showcase community support. Produced or amended menus and item selections in conjunction with food and beverage team. Performed financial analysis and recommended effective methods to cut costs. Initiated software based inventory control system to manage inventory and analyze food cost. Coordinated and executed menu planning, recipe development and daily restaurant operations. Monitored quality, presentation and proper quantities of plated food across line. Created new menu items, managed food expenses and supervised quality to ensure adherence to standards. Oversaw hiring and development of kitchen employees as well as trained numerous kitchen personnel from ground up to take on challenging stations such as Sous-Chef and Chef de Cuisine. Continually aware of dramatic changes to kitchens, including Health Department Standards and customer requests for healthier food options. Monitored kitchen area and staff to ensure overall safety and proper food handling techniques.",
  'http://data.europa.eu/esco/occupation/01484951-15e6-4b88-a20f-1201868d36a0',
  'train'),
 ('Human Resources Representative',
  'Provide daily support for benefits administration, maintain compensation system, administer various HR functions, interpret personnel policies, provide training and outreach activities, support retirees, and provide technical support to HR representatives.',
  'http://data.europa.eu/esco/occupation/d8ed1703-9c03-4ea0-83cc-b6169bc54ffd',
  'train'),
 ('Assistant Rental Manager',
  "Manage profit-and-loss reports, control expenses, and implement comprehensive business development and marketing plans. Make weekly marketing and sales calls to area accounts. Top regional performer in sales, customer service, and generating corporate leads. Manage, shape, and develop employees' careers with the company. Responsible for choosing, interviewing and hiring part time staff; while supervising, teaching, evaluating and developing full time employees. Decrease costs through reduction in bad debt, decrease in payroll, control of fleet costs, and mitigate unneeded expenses. Responsible for over one million dollars in assets. Accountable for locating vehicles when findability and payability are lost on a car. Managing proper underwriting on rental contracts.",
  'http://data.europa.eu/esco/occupation/de31a27f-c6ba-4d4f-87cd-b405e1852121',
  'train'),
 ('Floor Manager',
  '- Served as a direct liaison between clients and technical staff.\n- Ensured superior customer service by managing all aspects of customer interaction.\n- Created and maintained staff schedules.\n- Assisted in ensuring seamless and productive day-to-day operations.\n- Monitored and tracked daily, yearly, and weekly sales in all departments.\n- Promoted to Salon Manager of the Greenwich, CT location in September 2010.',
  'http://data.europa.eu/esco/occupation/a79d9e58-36be-4e67-a4db-ea6c8ff445fc',
  'train'),
 ('Accountant',
  "Sources items through the compilation of vendor information and bidding processes. Selects preferred vendors based on competitive pricing, products' liabilities, payment terms, and ETA's. Creates auditing processes for inventory management. Selects bank statements randomly to ensure that disbursements were authorized and signed by two individuals. Ensures three-way matches of requisitions, purchase orders, and good receipts. Performs data analysis on bank statements to ensure that all reconciled items are processed in a timely manner. Audits the database demographic to better understand clientele of the company and to maximize customer satisfaction level. Completes month-end journal entries and month-end reports. Prepares bank reconciliations and ensures all reconciling items are resolved in a timely manner. Organizes monthly, quarterly, and annual financial statements.",
  'http://data.europa.eu/esco/occupation/eda0d957-3c3c-4139-b89a-a18bc9e18897',
  'train'),
 ('Systems Programmer',
  'Designed, developed, tested, and supported a real-time client/server application for messaging and communications between VAX/VMS and IBM systems. The application tracked train movement and locations. Originally written in assembly language and later converted to C. Provided general system and network administration support.',
  'http://data.europa.eu/esco/occupation/f2b15a0e-e65a-438a-affb-29b9d50b77d1',
  'train'),
 ('Permit Coordinator',
  'Served more than 70 municipalities, helping builders expedite the permitting process. Utilized technical knowledge of construction and built trusting relationships with builders and municipalities to save time and money in the permitting process.',
  'http://data.europa.eu/esco/occupation/643a2225-6a01-4899-81b0-e867ca09b9c9',
  'train'),
 ('Registrar',
  'Maintained administrative processes and organized file system. Coordinated educational department functions and meetings. Updated student records and improved registration processes. Provided support to Executive Director and Admissions Department. Standardized filing system and improved communication efficiency. Prepared student records and handled confidential information.',
  'http://data.europa.eu/esco/occupation/55b4faa3-286f-4fc8-ac67-8bbb97d08820',
  'train'),
 ('Lead Maintenance Mechanic',
  '- Supervised a team of four Mechanics and provided technical guidance and skill development.\n- Executed preventative maintenance program on various conveyor systems.\n- Coordinated with management on equipment service and availability.\n- Oversaw facility maintenance duties and handled parts purchasing.\n- Served as primary point of contact for technical and IT issues.\n- Implemented CCTV as an IP solution and developed equipment preventative maintenance program.',
  'http://data.europa.eu/esco/occupation/a9b20949-897b-481f-8642-d1f69263baff',
  'val'),
 ('Special Projects',

In [14]:
df.shape

NameError: name 'df' is not defined

In [18]:
df.columns

Index(['Unnamed: 0', 'raw_title', 'raw_description', 'esco_title',
       'esco_description', 'esco_id', 'job_id'],
      dtype='object')

In [17]:
# Create DataFrame from unique_pairs
unique_df = pd.DataFrame(list(unique_pairs), columns=['raw_title', 'raw_description', 'esco_id', 'split'])
unique_df

,raw_title,raw_description,esco_id,split
0,"Manager, Partner Marketing",Directed partner relations and partner marketi...,http://data.europa.eu/esco/occupation/6fcf4638...,train
1,"Merchandiser, Sales","Worked for Southern Wine & Spirits, a family o...",http://data.europa.eu/esco/occupation/f1fcad3b...,train
2,Digital Merchandising Analyst,Report on sales trends and observations to inf...,http://data.europa.eu/esco/occupation/1dd7c3cb...,val
3,Property Accountant,Assisted the GM in financial forecasts and bud...,http://data.europa.eu/esco/occupation/0f5b4653...,train
4,Electrical Power Production Apprentice,"Installed, operated, and maintained 37 permane...",http://data.europa.eu/esco/occupation/72381086...,train
...,...,...,...,...
9880,Consultant,Helped customers select products that best fit...,http://data.europa.eu/esco/occupation/13d1b2b4...,train
9881,Administrative Executive and Accountant,"Provided excellent customer service, assisted ...",http://data.europa.eu/esco/occupation/6e6839b6...,train
9882,Apparel Associate,- Greeted customers and ascertained their want...,http://data.europa.eu/esco/occupation/0b15375e...,train
9883,Associate Producer,Production company that aired on WSB-TV. Proje...,http://data.europa.eu/esco/occupation/52b9e8dc...,train
9884,Sales Advisor,"Prepare, present, and encourage sales of speci...",http://data.europa.eu/esco/occupation/547b304b...,train

In [20]:
df_occ.columns

Index(['conceptType', 'conceptUri', 'iscoGroup', 'preferredLabel', 'altLabels',
       'hiddenLabels', 'status', 'modifiedDate', 'regulatedProfessionNote',
       'scopeNote', 'definition', 'inScheme', 'description', 'code',
       'iscoGroup_1', 'iscoGroup_2', 'iscoGroup_3', 'iscoGroup_4'],
      dtype='object')

In [29]:
df_occ.merge(unique_df.query('split == "test"'), left_on='conceptUri', right_on='esco_id', how='left').iscoGroup_1.value_counts().sort_index()

iscoGroup_1
0      22
1     533
2    1067
3     771
4     175
5     267
6      44
7     397
8     354
9      82
Name: count, dtype: int64

In [25]:
df_occ.iscoGroup_1.unique()

array([2, 8, 7, 3, 5, 1, 6, 4, 9])

In [17]:
unique_df.groupby(['raw_title', 'raw_description']).esco_id.nunique().sort_values()

raw_title                                                     raw_description
1st and 2nd Grade Sunday School Teacher                       - Planned lessons and created classroom materials to instruct students about Judaism.\n- Established and enforced rules for behavior and procedures for maintaining order among a class of 18 students.\n- Created and enforced child-based hands-on curriculum to promote student interest and receptive learning.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
21st Century Site Coordinator                                 Coordinated academic instruction and violence prevention programs in after school programs at Star Elementary and Rogers Middle Schools. Managed budget, supplies, equipment, and scheduling activities for students.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
25Live Functional Administrator/Supervisor of I.T. Help Desk  Communicate with and identify the needs of Resource 25 usage for staff members within the University. Set boundaries for Web Viewers and Users. Respond to space requests. As the University's appointed Resource 25 Administrator, all information on Resource 25 must be kept current by deleting space/creating new space. Run weekly reports giving key information as to the events occurring on campus and the Sports Complex. E-mail to members of the events Committee. Take leadership role at the Events meeting which precedes the events meeting. Run weekly reports on Sports Complex activities and e-mail to Village of Lisle. Develop, review and implement policies and procedures for the Resource 25 space reservation process. Other Functions: Keep current and communicate with IT on the need for Resource 25 upgrades and research and identify the need for efficiencies such as the Resource 25 and PeopleSoft interface. Train authorized Benedictine staff members to use Resource 25 at the User level. Maintain/update Resource 25 web site. Assist areas within the Office of Operations during summer/vacation period. Handle/answer inbound requests from customers. Answer phones professionally. Answer Service Desk requests and tickets in a timely manner. Use questioning and listening skills that support effective telephone communication. Support and provide superior service to customers via various communication media. Resolve customer support related issues and provide customer with proper resolution, via troubleshooting techniques. Deliver prompt and accurate assistance, with the highest levels of quality service and professionalism. Research required information using available resources. Transfer requests with specific/complex inquiries to appropriate department or person. Use an effective approach to handle special telephone tasks like call transfers, taking messages, call backs, holds, interruptions, and unintentional disconnects. Recognize, document and alert the supervisor of trends in the customer requests. Suggest process improvements for the department. Retain and execute proficient knowledge of daily processes and procedures. Assist with CSR training. Assist fellow CSRs with challenging situations. Mentor CSRs. Act as go-to point person for the department. Act as a Team Lead in the absence of the Service Desk Team Lead on an as needed basis. Perform CSR responsibilities based on Benedictine University's mission, vision, direction and business objectives. Reinforce company and department policies, processes, and procedures. Assist with special projects and other duties as assigned. Ability to work successfully as part of a team.    1
2nd Grade Replacement Teacher                                 Implemented positive behavior management using the color system. Developed clear objectives for students and parents for all lessons and activities. Designed differentiated common core lesson plans and activities to meet the needs of all learners. Enhanced lessons using Smartboard technology, I-Pads, and computer lab. Assessed student growth through informal and formal assessments. Developed lessons in accordance to student reading levels determined by quarterly running record testing. Maintained positive collaboration and communication with parents through weekly newsletters, weekly student progress updates, emails, and conferences. Attended in-services and staff meetings, maintaining strong relationships with fellow staff and administrators.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
2nd Grade Teacher                                             Follow the district's curriculum for 2nd grade and implement daily lesson plans for 2nd grade, administer tests and analyze student performance. Conduct group reading activities. Foster a classroom environment conducive to learning and promoting excellent student/teacher interaction. Participate in faculty/parent conferences. Contact parents by phone and email to discuss student issues and concerns. Follow district policies and procedures for teachers. Document student performance/concerns for student records. Remain professional and ethical at all times.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ..
Youth Program Assistant                                       Serve as liaison between CES and the school to promote program teaching opportunities to school staff, increase the number and the variety of program offerings available, and increase awareness of programs available to families. Partner with Youth Programs Coordinator (YPC), principal, and other school staff to assess youth and parent program needs. Work with YPC in developing and implementing a plan for future opportunities. Work with CES staff to effectively market CES programs and increase enrollment. Monitor scheduled CES activities in assigned buildings and community locations. Ensure after school class safety procedures are being followed. Respond to any safety or special concerns as they arrive and provide Crisis Management/Response as needed, including First Aid, CPR, AED, and evacuation. Promote a safe environment by following After School Class Safety Procedures. Assist CES with special events.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1

In [15]:
# additional task here, you can skip
import pandas as pd

df_master_2 = pd.read_csv(r'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/decorte_master_2.csv')

In [21]:
df_master_2.merge(
    unique_df, 
    left_on=['raw_title', 'raw_description', 'esco_id'],
    right_on=['raw_title', 'raw_description', 'esco_id'],
    how='left').drop(columns=['Unnamed: 0']).to_csv('/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/decorte_master_3.csv')

In [16]:
df_master_2.shape

(9885, 8)

In [4]:
df_master_2['l_raw_title'] = df_master_2.raw_title.apply(lambda x: x.lower())

df_master_2.drop_duplicates(subset='l_raw_title')

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id,skill_brief,l_raw_title
0,0,Line Cook,- Prepped food for the line and cooked appetiz...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,0,Skills needed for a Line Cook role include cul...,line cook
1,1,Line Chef,- Prepared food for the kitchen and created sp...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,1,Skills needed for a Line Chef role include pro...,line chef
2,2,Executive Chef,- Promoted from rounds chef to sous chef in 20...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,2,Skills needed for the Executive Chef role incl...,executive chef
3,3,Banquet Cook 2( Lead Cook),- Attended daily BEO meetings\n- Prepped and f...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,3,Skills needed for a Banquet Cook 2 (Lead Cook)...,banquet cook 2( lead cook)
4,4,Kitchen Supervisor,- Oversaw the am shift\n- Part of a renovation...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,4,Skills needed for a Kitchen Supervisor role in...,kitchen supervisor
...,...,...,...,...,...,...,...,...,...
7924,7924,General Manager and Board Member,Led a team of 100 associates in all facets of ...,business manager,Business managers are responsible for setting ...,http://data.europa.eu/esco/occupation/544cd9cf...,7924,Skills needed for the General Manager and Boar...,general manager and board member
7925,7925,Intraday Operations Analyst,Supervised a team responsible for intraday wor...,call centre supervisor,Call centre supervisors oversee call centre em...,http://data.europa.eu/esco/occupation/6aa78e46...,7925,Skills needed for an Intraday Operations Analy...,intraday operations analyst
7927,7927,Workforce Specialist (WFM),Ensured optimum intraday staffing and performa...,contact centre supervisor,Contact centre supervisors oversee and coordin...,http://data.europa.eu/esco/occupation/9d2aae3e...,7927,Skills needed for a Workforce Specialist (WFM)...,workforce specialist (wfm)
7928,7928,Sr. Workforce Manager,Reduced non-productive agent time by 33% for a...,contact centre manager,Contact centre managers coordinate and plan th...,http://data.europa.eu/esco/occupation/f5166c6b...,7928,Skills needed for a Sr. Workforce Manager role...,sr. workforce manager
7929,7929,Workforce Planning Manager,Managed a team of five workforce and Kronos an...,call centre manager,Call centre managers set the objectives of the...,http://data.europa.eu/esco/occupation/dd25a2b0...,7929,Skills needed for a Workforce Planning Manager...,workforce planning manager

In [46]:
df_aug_2 = pd.read_csv(r'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/processed/augmentation/augmented_decorte_occupations_with_desc_2.csv')

In [50]:
df_test_only = df_master_2.merge(unique_df, left_on=['raw_title', 'raw_description', 'esco_id'], right_on=['raw_title', 'raw_description', 'esco_id']).query('split=="test"')

In [52]:
df_test_only.merge(df_occ[['iscoGroup','conceptUri']], left_on='esco_id', right_on='conceptUri', how='left').to_csv('/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/category_test_split_isco.csv')

In [20]:
import pandas as pd
df=pd.read_csv(r'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/category_test_split_isco.csv')

In [22]:
df.shape

(1046, 12)

In [23]:
df.head()

,Unnamed: 0.1,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id,skill_brief,split,iscoGroup,conceptUri
0,0,6163,Chef de Cuisine,Worked with executive chef to develop and exec...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,6163,Skills needed for the Chef de Cuisine role inc...,test,3434,http://data.europa.eu/esco/occupation/01484951...
1,1,6164,Chef/General Manager,Developed food and beverage menu for a new fas...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,6164,Skills needed for this role include culinary e...,test,1412,http://data.europa.eu/esco/occupation/d5eb6150...
2,2,6165,Executive Chef,Co-ordinated and executed meals for various co...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,6165,Skills needed for an Executive Chef role inclu...,test,3434,http://data.europa.eu/esco/occupation/01484951...
3,3,6166,"Lead Cook/Kitchen Trainer, Kitchen Manager",- Cook and Prepare meals for our guest.\n- Res...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,6166,Skills needed for this role include strong coo...,test,5120,http://data.europa.eu/esco/occupation/90f75f67...
4,4,6167,Lead Cook,- Put in product orders for the Restaurant.\n-...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,6167,Skills needed for the Lead Cook role include s...,test,3434,http://data.europa.eu/esco/occupation/01484951...

In [20]:
import numpy as np
unique_df['new_job_id'] = np.arange(1,len(unique_df)+1)

In [21]:
df.merge(unique_df, left_on=['raw_title', 'raw_description', 'esco_id'], right_on = ['raw_title', 'raw_description', 'esco_id'], how='left').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7930 entries, 0 to 7929
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        7930 non-null   int64
 1   raw_title         7930 non-null   object
 2   raw_description   7922 non-null   object
 3   esco_title        7930 non-null   object
 4   esco_description  7928 non-null   object
 5   esco_id           7930 non-null   object
 6   job_id            7930 non-null   int64
 7   new_job_id        7920 non-null   float64
dtypes: float64(1), int64(2), object(5)
memory usage: 495.8+ KB

In [22]:
df.merge(unique_df, left_on=['raw_title', 'raw_description', 'esco_id'], right_on = ['raw_title', 'raw_description', 'esco_id'], how='left').query('new_job_id.isna()')

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id,new_job_id
214,214,Med Tech,Promoted continuity of care by accurately and ...,residential care home worker,NaN,http://data.europa.eu/esco/occupation/81309031...,214,NaN
1266,1266,"Trainer, Bartender, Server",NaN,bartender,Bartenders serve alcoholic or non-alcoholic dr...,http://data.europa.eu/esco/occupation/2f5e38a0...,1266,NaN
2082,2082,Accounting Clerk,NaN,bookkeeper,Bookkeepers record and assemble the day-to-day...,http://data.europa.eu/esco/occupation/c3aae59e...,2082,NaN
4881,4881,Management Trainee,NaN,management assistant,Management assistants perform varied types of ...,http://data.europa.eu/esco/occupation/8cce40c1...,4881,NaN
4882,4882,Delivery Lead,NaN,car and van delivery driver,Car and van delivery drivers transport goods a...,http://data.europa.eu/esco/occupation/0c408028...,4882,NaN
5384,5384,Key Hourly Manager,NaN,supermarket manager,Supermarket managers are responsible for activ...,http://data.europa.eu/esco/occupation/b7744a45...,5384,NaN
5385,5385,Assistant Supervisor/Head Bartender,NaN,bartender,Bartenders serve alcoholic or non-alcoholic dr...,http://data.europa.eu/esco/occupation/2f5e38a0...,5385,NaN
5691,5691,Math Teacher,NaN,mathematics teacher at secondary school,Mathematics teachers at secondary schools prov...,http://data.europa.eu/esco/occupation/f0e1cc13...,5691,NaN
6464,301,Caregiver,"- Assessed the need for, ordered, obtained, an...",residential care home worker,NaN,http://data.europa.eu/esco/occupation/81309031...,6464,NaN
7543,454,Regional Training Coordinator and Residential ...,NaN,corporate training manager,Corporate training managers coordinate all the...,http://data.europa.eu/esco/occupation/a14e96a7...,7543,NaN

In [23]:
unique_df.query('raw_title == "Med Tech"')

,raw_title,raw_description,esco_id,new_job_id
7954,Med Tech,Promoted continuity of care by accurately and ...,http://data.europa.eu/esco/occupation/f4525ed8...,7955

In [24]:
# Note for tomorrow: So many values in unique df but not in master df. Extract wrong ones, apply augmentation on them, concat to master df, re-run everything!

In [25]:
df.query("esco_id == 'http://data.europa.eu/esco/occupation/81309031-dad2-4a7a-bde6-7f6e518f89ff'")

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id
214,214,Med Tech,Promoted continuity of care by accurately and ...,residential care home worker,NaN,http://data.europa.eu/esco/occupation/81309031...,214
6464,301,Caregiver,"- Assessed the need for, ordered, obtained, an...",residential care home worker,NaN,http://data.europa.eu/esco/occupation/81309031...,6464

In [26]:
unique_df.query("esco_id == 'http://data.europa.eu/esco/occupation/f4525ed8-54eb-4a3b-90db-55cc01b0d9fd'")

,raw_title,raw_description,esco_id,new_job_id
76,Healthcare Provider,Provided healthcare for at-home patients.,http://data.europa.eu/esco/occupation/f4525ed8...,77
1032,Home Healthcare Provider,"Provided home healthcare services, including a...",http://data.europa.eu/esco/occupation/f4525ed8...,1033
2877,Caregiver,"- Assessed the need for, ordered, obtained, an...",http://data.europa.eu/esco/occupation/f4525ed8...,2878
5733,Healthcare Provider,"Through Manna, I provided care for a mentally ...",http://data.europa.eu/esco/occupation/f4525ed8...,5734
7904,Private Duty Home Healthcare Aide,Supported healthy nutrition by cooking meals a...,http://data.europa.eu/esco/occupation/f4525ed8...,7905
7954,Med Tech,Promoted continuity of care by accurately and ...,http://data.europa.eu/esco/occupation/f4525ed8...,7955
9824,Stay at home mom,Took a break from work to focus on being a sta...,http://data.europa.eu/esco/occupation/f4525ed8...,9825

In [27]:
unique_df.shape

(9885, 4)

In [28]:
unique_df[['raw_title', 'raw_description']].drop_duplicates().shape

(9885, 2)

In [29]:
final_df = unique_df.merge(df_occ[['conceptUri', 'preferredLabel', 'description']], left_on='esco_id', right_on='conceptUri')

In [30]:
final_df.head()

,raw_title,raw_description,esco_id,new_job_id,conceptUri,preferredLabel,description
0,Associate Fund Controller,Performed quarterly and annual close procedure...,http://data.europa.eu/esco/occupation/e20eee17...,1,http://data.europa.eu/esco/occupation/e20eee17...,asset manager,Asset managers invest the money of a client in...
1,Online English Tutor,- Analyzed student progress to adjust lesson p...,http://data.europa.eu/esco/occupation/59bce29f...,2,http://data.europa.eu/esco/occupation/59bce29f...,tutor,Tutors provide personalised education to the c...
2,Assistant Director of Polar Expeditions,Handled sales and procurement of polar adventu...,http://data.europa.eu/esco/occupation/6ce3c372...,3,http://data.europa.eu/esco/occupation/6ce3c372...,tourism product manager,"Tourism product managers analyse the market, r..."
3,Assistant,"Assisted directors, board of directors, and hu...",http://data.europa.eu/esco/occupation/8cce40c1...,4,http://data.europa.eu/esco/occupation/8cce40c1...,management assistant,Management assistants perform varied types of ...
4,Product Designer (contract),Worked with a creative team to develop ideas a...,http://data.europa.eu/esco/occupation/ab7bccb2...,5,http://data.europa.eu/esco/occupation/ab7bccb2...,industrial designer,Industrial designers work out ideas and develo...

In [31]:
df.columns

Index(['Unnamed: 0', 'raw_title', 'raw_description', 'esco_title',
       'esco_description', 'esco_id', 'job_id'],
      dtype='object')

In [32]:
final_df = final_df.rename(
    columns={
        'preferredLabel':'esco_title',
        'description': 'esco_description'
    }
)[['raw_title', 'raw_description', 'esco_title', 'esco_description', 'esco_id', 'new_job_id']]

In [33]:
df.merge(final_df, left_on=['raw_title', 'raw_description', 'esco_id'], right_on=['raw_title', 'raw_description', 'esco_id'], how='left').sort_values('new_job_id')

,Unnamed: 0,raw_title,raw_description,esco_title_x,esco_description_x,esco_id,job_id,esco_title_y,esco_description_y,new_job_id
4469,4469,Associate Fund Controller,Performed quarterly and annual close procedure...,asset manager,Asset managers invest the money of a client in...,http://data.europa.eu/esco/occupation/e20eee17...,4469,asset manager,Asset managers invest the money of a client in...,1.0
5374,5374,Online English Tutor,- Analyzed student progress to adjust lesson p...,tutor,Tutors provide personalised education to the c...,http://data.europa.eu/esco/occupation/59bce29f...,5374,tutor,Tutors provide personalised education to the c...,2.0
1070,1070,Assistant Director of Polar Expeditions,Handled sales and procurement of polar adventu...,tourism product manager,"Tourism product managers analyse the market, r...",http://data.europa.eu/esco/occupation/6ce3c372...,1070,tourism product manager,"Tourism product managers analyse the market, r...",3.0
1065,1065,Assistant,"Assisted directors, board of directors, and hu...",management assistant,Management assistants perform varied types of ...,http://data.europa.eu/esco/occupation/8cce40c1...,1065,management assistant,Management assistants perform varied types of ...,4.0
4179,4179,Product Designer (contract),Worked with a creative team to develop ideas a...,industrial designer,Industrial designers work out ideas and develo...,http://data.europa.eu/esco/occupation/ab7bccb2...,4179,industrial designer,Industrial designers work out ideas and develo...,5.0
...,...,...,...,...,...,...,...,...,...,...
5384,5384,Key Hourly Manager,NaN,supermarket manager,Supermarket managers are responsible for activ...,http://data.europa.eu/esco/occupation/b7744a45...,5384,NaN,NaN,NaN
5385,5385,Assistant Supervisor/Head Bartender,NaN,bartender,Bartenders serve alcoholic or non-alcoholic dr...,http://data.europa.eu/esco/occupation/2f5e38a0...,5385,NaN,NaN,NaN
5691,5691,Math Teacher,NaN,mathematics teacher at secondary school,Mathematics teachers at secondary schools prov...,http://data.europa.eu/esco/occupation/f0e1cc13...,5691,NaN,NaN,NaN
6464,301,Caregiver,"- Assessed the need for, ordered, obtained, an...",residential care home worker,NaN,http://data.europa.eu/esco/occupation/81309031...,6464,NaN,NaN,NaN
7543,454,Regional Training Coordinator and Residential ...,NaN,corporate training manager,Corporate training managers coordinate all the...,http://data.europa.eu/esco/occupation/a14e96a7...,7543,NaN,NaN,NaN

In [34]:
replacements_title = {
        'ICT security engineer': 'cyber incident responder',
        'ict security engineer': 'cyber incident responder',
        'care at home worker': 'care home worker',
        'residential care home worker': 'care home worker',
        'ICT security manager': 'cybersecurity risk manager',
        'ict security manager': 'cybersecurity risk manager',
        'care at home worker': 'care home worker',
        'handyman': 'handyperson',
        'corporate banking manager': 'corporate banking adviser',
    }

replacements_uri = {
        'http://data.europa.eu/esco/occupation/81309031-dad2-4a7a-bde6-7f6e518f89ff': 
        'http://data.europa.eu/esco/occupation/f4525ed8-54eb-4a3b-90db-55cc01b0d9fd'
    }

In [35]:
df_adj = df.copy()

df_adj['esco_title'] = df_adj['esco_title'].replace(replacements_title)
df_adj['esco_id'] = df_adj['esco_id'].replace(replacements_uri)

In [36]:
df_adj['raw_description'].fillna('na', inplace=True)

/tmp/ipykernel_722487/1315433252.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_adj['raw_description'].fillna('na', inplace=True)

In [37]:
df.merge(final_df, left_on=['raw_title', 'raw_description', 'esco_id'], right_on=['raw_title', 'raw_description', 'esco_id'], how='left').sort_values('new_job_id').info()

<class 'pandas.core.frame.DataFrame'>
Index: 7930 entries, 4469 to 7543
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          7930 non-null   int64
 1   raw_title           7930 non-null   object
 2   raw_description     7922 non-null   object
 3   esco_title_x        7930 non-null   object
 4   esco_description_x  7928 non-null   object
 5   esco_id             7930 non-null   object
 6   job_id              7930 non-null   int64
 7   esco_title_y        7920 non-null   object
 8   esco_description_y  7920 non-null   object
 9   new_job_id          7920 non-null   float64
dtypes: float64(1), int64(2), object(7)
memory usage: 681.5+ KB

In [38]:
df_adj.merge(final_df, left_on=['raw_title', 'raw_description', 'esco_id'], right_on=['raw_title', 'raw_description', 'esco_id'], how='left').sort_values('new_job_id').info()

<class 'pandas.core.frame.DataFrame'>
Index: 7930 entries, 4469 to 4254
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          7930 non-null   int64
 1   raw_title           7930 non-null   object
 2   raw_description     7930 non-null   object
 3   esco_title_x        7930 non-null   object
 4   esco_description_x  7928 non-null   object
 5   esco_id             7930 non-null   object
 6   job_id              7930 non-null   int64
 7   esco_title_y        7930 non-null   object
 8   esco_description_y  7930 non-null   object
 9   new_job_id          7930 non-null   int64
dtypes: int64(3), object(7)
memory usage: 681.5+ KB

In [39]:
final_with_old = df_adj.merge(final_df, left_on=['raw_title', 'raw_description', 'esco_id'], right_on=['raw_title', 'raw_description', 'esco_id'], how='right').sort_values('job_id')
final_with_old['new_job_id'] = np.arange(final_with_old.shape[0])

In [40]:
final_with_old.query('esco_title_x != esco_title_y').info()

<class 'pandas.core.frame.DataFrame'>
Index: 1955 entries, 11 to 9883
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          0 non-null      float64
 1   raw_title           1955 non-null   object
 2   raw_description     1955 non-null   object
 3   esco_title_x        0 non-null      object
 4   esco_description_x  0 non-null      object
 5   esco_id             1955 non-null   object
 6   job_id              0 non-null      float64
 7   esco_title_y        1955 non-null   object
 8   esco_description_y  1955 non-null   object
 9   new_job_id          1955 non-null   int64
dtypes: float64(2), int64(1), object(7)
memory usage: 168.0+ KB

In [41]:
final_with_old.query('esco_description_x != esco_description_y')

,Unnamed: 0,raw_title,raw_description,esco_title_x,esco_description_x,esco_id,job_id,esco_title_y,esco_description_y,new_job_id
7954,214.0,Med Tech,Promoted continuity of care by accurately and ...,care home worker,NaN,http://data.europa.eu/esco/occupation/f4525ed8...,214.0,care home worker,Care home workers provide domiciliary services...,214
2877,301.0,Caregiver,"- Assessed the need for, ordered, obtained, an...",care home worker,NaN,http://data.europa.eu/esco/occupation/f4525ed8...,6464.0,care home worker,Care home workers provide domiciliary services...,6464
11,NaN,Controller,Managed the financial health of a provider of ...,NaN,NaN,http://data.europa.eu/esco/occupation/5e5b1b61...,NaN,financial controller,Financial controllers handle all tasks related...,7930
12,NaN,Office Assistant,"Greeted persons entering establishment, determ...",NaN,NaN,http://data.europa.eu/esco/occupation/044d78cc...,NaN,administrative assistant,Administrative assistants provide administrati...,7931
18,NaN,Software Engineer,- Designed and developed an application to mig...,NaN,NaN,http://data.europa.eu/esco/occupation/f2b15a0e...,NaN,software developer,Software developers implement or program all k...,7932
...,...,...,...,...,...,...,...,...,...,...
9865,NaN,General Manager,Oversaw sales and ordering of products. Manage...,NaN,NaN,http://data.europa.eu/esco/occupation/544cd9cf...,NaN,business manager,Business managers are responsible for setting ...,9880
9866,NaN,Senior Accountant,"Reconcile various balance sheet accounts, incl...",NaN,NaN,http://data.europa.eu/esco/occupation/eda0d957...,NaN,accountant,Accountants review and analyse financial state...,9881
9867,NaN,Human Resources Specialist,Coordinated all recruitment and on-boarding ef...,NaN,NaN,http://data.europa.eu/esco/occupation/f605bcd2...,NaN,human resources manager,"Human resources managers plan, design and impl...",9882
9874,NaN,Tutor,Tutored students in one-on-one and group class...,NaN,NaN,http://data.europa.eu/esco/occupation/59bce29f...,NaN,tutor,Tutors provide personalised education to the c...,9883
9883,NaN,Accountant,"Prepared payroll, sales and use tax, employmen...",NaN,NaN,http://data.europa.eu/esco/occupation/eda0d957...,NaN,accountant,Accountants review and analyse financial state...,9884

In [42]:
#final_with_old=final_with_old.drop(columns=['Unnamed: 0', 'esco_title_x', 'esco_description_x'])
#final_with_old.job_id = final_with_old.job_id.astype(int)
final_with_old.rename(
    columns={
        'esco_title_y':'esco_title',
        'esco_description_y':'esco_description'
    },
    inplace=True
)

In [43]:
final_with_old.query("raw_title.str.contains('Delivery')")

,Unnamed: 0,raw_title,raw_description,esco_title_x,esco_description_x,esco_id,job_id,esco_title,esco_description,new_job_id
861,106.0,Warehouse Worker/Delivery Driver,- Assisted Warehouse Manager and Shop Manager ...,cargo vehicle driver,Cargo vehicle drivers operate vehicles such as...,http://data.europa.eu/esco/occupation/45037d43...,106.0,cargo vehicle driver,Cargo vehicle drivers operate vehicles such as...,106
2018,1281.0,Bay Delivery Driver,Worked with upper management in major food acc...,cargo vehicle driver,Cargo vehicle drivers operate vehicles such as...,http://data.europa.eu/esco/occupation/45037d43...,1281.0,cargo vehicle driver,Cargo vehicle drivers operate vehicles such as...,1281
7839,1516.0,"Regional Manager, Professional Services Delivery",Developed and deployed project management stan...,project manager,Project managers oversee the project on a dail...,http://data.europa.eu/esco/occupation/bea99fea...,1516.0,project manager,Project managers oversee the project on a dail...,1516
6637,1788.0,Delivery Driver,Delivered products to local homes and business...,car and van delivery driver,Car and van delivery drivers transport goods a...,http://data.europa.eu/esco/occupation/0c408028...,1788.0,car and van delivery driver,Car and van delivery drivers transport goods a...,1788
299,2164.0,Service Delivery Coordinator,Initially hired in the Centralized Order Entry...,customer service representative,Customer service representatives handle compla...,http://data.europa.eu/esco/occupation/13d1b2b4...,2164.0,customer service representative,Customer service representatives handle compla...,2164
8960,3211.0,Team Leader / Service Delivery Coordinator / S...,Started as a CSR and promoted to Team Leader o...,call centre supervisor,Call centre supervisors oversee call centre em...,http://data.europa.eu/esco/occupation/6aa78e46...,3211.0,call centre supervisor,Call centre supervisors oversee call centre em...,3211
8496,3908.0,Delivery Driver,Delivered product and filled vending machines ...,cargo vehicle driver,Cargo vehicle drivers operate vehicles such as...,http://data.europa.eu/esco/occupation/45037d43...,3908.0,cargo vehicle driver,Cargo vehicle drivers operate vehicles such as...,3908
3135,4329.0,CSR/Delivery/Warehouse,"Dry van delivery, loading and unloading, custo...",stevedore,"Stevedores sort, handle, load and unload freig...",http://data.europa.eu/esco/occupation/b567a979...,4329.0,stevedore,"Stevedores sort, handle, load and unload freig...",4329
7271,4882.0,Delivery Lead,na,car and van delivery driver,Car and van delivery drivers transport goods a...,http://data.europa.eu/esco/occupation/0c408028...,4882.0,car and van delivery driver,Car and van delivery drivers transport goods a...,4882
202,4885.0,Online Advertising Delivery Manager,Operated in the fast-paced Online Advertising ...,advertising manager,Advertising managers perform the implementatio...,http://data.europa.eu/esco/occupation/4ebf2dae...,4885.0,advertising manager,Advertising managers perform the implementatio...,4885
108,5606.0,Healthcare Documentation Services Delivery Man...,Managed healthcare documentation services to e...,medical records manager,Medical records managers are responsible for m...,http://data.europa.eu/esco/occupation/983c2816...,5606.0,medical records manager,Medical records managers are responsible for m...,5606
4093,5990.0,Business Systems Delivery Consultant,Worked as a business systems delivery consulta...,ICT business analyst,ICT business analysts are in charge of analysi...,http://data.europa.eu/esco/occupation/fe0fa514...,5990.0,ICT business analyst,ICT business analysts are in charge of analysi...,5990
3548,554.0,Delivery Driver,- Executing delivery tasks as assigned\n- Assi...,car and van delivery driver,Car and van delivery drivers transport goods a...,http://data.europa.eu/esco/occupation/0c408028...,6717.0,car and van delivery driver,Car and van delivery drivers transport goods a...,6717
7780,868.0,Delivery Driver,- Drove vehicles with capacities under three t...,cargo vehicle driver,Cargo vehicle drivers operate vehicles such as...,http://data.europa.eu/esco/occupation/45037d43...,7031.0,cargo vehicle driver,Cargo vehicle drivers operate vehicles such as...,7031
4725,882.0,"Manager, Service Delivery Systems",Led the implementation of outbound call center...,call centre manager,Call centre managers set the objectives of the...,http://data.europa.eu/esco/occupation/dd25a2b0...,7045.0,call centre manager,Call centre managers set the objectives of the...,7045
2212,220.0,Florist Helper / Delivery Driver,Communicated information to customers about pr...,customer service representative,Customer service representatives handle compla...,http://data.europa.eu/esco/occupation/13d1b2b4...,7309.0,customer service representative,Customer service representatives handle compla...,7309
1843,NaN,Delivery Driver,"Coordinated and delivered orders to customers,...",NaN,NaN,http://data.europa.eu/esco/occupation/0c408028...,NaN,car and van delivery driver,Car and van delivery drivers transport goods a...,8248
8572,NaN,Delivery Driver,Operated and maintained heavy equipment safely...,NaN,NaN,http://data.europa.eu/esco/occupation/45037d43...,NaN,cargo vehicle driver,Cargo vehicle drivers operate vehicles such as...,9618

In [44]:
# Augmented data

df_aug = pd.read_csv(r'../data/processed/augmentation/augmented_decorte_occupations.csv')
df_aug_desc =  pd.read_csv(r'../data/processed/augmentation/augmented_decorte_occupations_with_desc.csv')

In [45]:
df_aug_desc.head()

,job_id,raw_title,raw_description,esco_title,esco_description,esco_id,skill_brief
0,0,Line Cook,- Prepped food for the line and cooked appetiz...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,Skills needed for a Line Cook role include cul...
1,1,Line Chef,- Prepared food for the kitchen and created sp...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,Skills needed for a Line Chef role include pro...
2,2,Executive Chef,- Promoted from rounds chef to sous chef in 20...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,Skills needed for the Executive Chef role incl...
3,3,Banquet Cook 2( Lead Cook),- Attended daily BEO meetings\n- Prepped and f...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,Skills needed for a Banquet Cook 2 (Lead Cook)...
4,4,Kitchen Supervisor,- Oversaw the am shift\n- Part of a renovation...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,Skills needed for a Kitchen Supervisor role in...

In [ ]:
df_aug_desc.merge(final_with_old, left_on='job_id', right_on='job_id', how='left').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7930 entries, 0 to 7929
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_id              7930 non-null   int64
 1   raw_title_x         7930 non-null   object
 2   raw_description_x   7922 non-null   object
 3   esco_title_x        7930 non-null   object
 4   esco_description_x  7928 non-null   object
 5   esco_id_x           7930 non-null   object
 6   skill_brief         7930 non-null   object
 7   Unnamed: 0          7930 non-null   float64
 8   raw_title_y         7930 non-null   object
 9   raw_description_y   7930 non-null   object
 10  esco_title_x        7930 non-null   object
 11  esco_description_x  7928 non-null   object
 12  esco_id_y           7930 non-null   object
 13  esco_title_y        7930 non-null   object
 14  esco_description_y  7930 non-null   object
 15  new_job_id          7930 non-null   int64
dtypes: float64(1), int64(2), object(13)
memory usage: 991.4+ KB

In [50]:
df_aug_desc.merge(final_with_old, left_on='job_id', right_on='job_id', how='right').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9885 entries, 0 to 9884
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_id              7930 non-null   float64
 1   raw_title_x         7930 non-null   object
 2   raw_description_x   7922 non-null   object
 3   esco_title_x        7930 non-null   object
 4   esco_description_x  7928 non-null   object
 5   esco_id_x           7930 non-null   object
 6   skill_brief         7930 non-null   object
 7   Unnamed: 0          7930 non-null   float64
 8   raw_title_y         9885 non-null   object
 9   raw_description_y   9885 non-null   object
 10  esco_title_x        7930 non-null   object
 11  esco_description_x  7928 non-null   object
 12  esco_id_y           9885 non-null   object
 13  esco_title_y        9885 non-null   object
 14  esco_description_y  9885 non-null   object
 15  new_job_id          9885 non-null   int64
dtypes: float64(2), int64(1), object(13)
memory usage: 1.2+ MB

In [52]:
merged = df_aug_desc.merge(final_with_old, left_on='job_id', right_on='job_id', how='right')

In [62]:
merged[merged.job_id.isna()].rename(
    columns={
        'esco_id_y': 'esco_id',
        'esco_title_y': 'esco_title',
        'esco_description_y': 'esco_description',
        'raw_title_y': 'raw_title',
        'raw_description_y': 'raw_description'
    }
)[[ 'raw_title', 'raw_description', 'esco_title',
       'esco_description', 'esco_id', 'new_job_id']].rename(columns={'new_job_id':'job_id'}).to_csv('/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/decorte_missing.csv')

In [58]:
df.head()

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id
0,0,Line Cook,- Prepped food for the line and cooked appetiz...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,0
1,1,Line Chef,- Prepared food for the kitchen and created sp...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,1
2,2,Executive Chef,- Promoted from rounds chef to sous chef in 20...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,2
3,3,Banquet Cook 2( Lead Cook),- Attended daily BEO meetings\n- Prepped and f...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,3
4,4,Kitchen Supervisor,- Oversaw the am shift\n- Part of a renovation...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,4

In [59]:
df.columns

Index(['Unnamed: 0', 'raw_title', 'raw_description', 'esco_title',
       'esco_description', 'esco_id', 'job_id'],
      dtype='object')

In [63]:
# Importing new augmented data
df_recent = pd.read_csv(r'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/processed/augmentation/augmented_decorte_missing_occupations.csv')

In [64]:
df_recent.head()

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id,skill_brief
0,7930,Controller,Managed the financial health of a provider of ...,financial controller,Financial controllers handle all tasks related...,http://data.europa.eu/esco/occupation/5e5b1b61...,7930,Skills needed for the Controller role include ...
1,7931,Office Assistant,"Greeted persons entering establishment, determ...",administrative assistant,Administrative assistants provide administrati...,http://data.europa.eu/esco/occupation/044d78cc...,7931,Skills needed for an Office Assistant role inc...
2,7932,Software Engineer,- Designed and developed an application to mig...,software developer,Software developers implement or program all k...,http://data.europa.eu/esco/occupation/f2b15a0e...,7932,Skills needed for a Software Engineer role inc...
3,7933,Software Engineer,Worked at Star Media and DPS. Developed video ...,software developer,Software developers implement or program all k...,http://data.europa.eu/esco/occupation/f2b15a0e...,7933,Skills needed for a Software Engineer in this ...
4,7934,History Teacher,Fifth grade social studies teacher at Thunderb...,secondary school teacher,Secondary school teachers provide education to...,http://data.europa.eu/esco/occupation/5efb2c08...,7934,Skills needed for a History Teacher role inclu...

In [65]:
df_aug.head()

,job_id,raw_title,raw_description,esco_title,esco_description,esco_id,skill_brief
0,0,Line Cook,- Prepped food for the line and cooked appetiz...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,A Line Cook needs to have strong culinary skil...
1,1,Line Chef,- Prepared food for the kitchen and created sp...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,"A Line Chef needs strong cooking skills, the a..."
2,2,Executive Chef,- Promoted from rounds chef to sous chef in 20...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,An Executive Chef needs strong leadership skil...
3,3,Banquet Cook 2( Lead Cook),- Attended daily BEO meetings\n- Prepped and f...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,A Banquet Cook 2 (Lead Cook) should have stron...
4,4,Kitchen Supervisor,- Oversaw the am shift\n- Part of a renovation...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,A Kitchen Supervisor typically needs strong le...

In [66]:
df_aug_desc.head()

,job_id,raw_title,raw_description,esco_title,esco_description,esco_id,skill_brief
0,0,Line Cook,- Prepped food for the line and cooked appetiz...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,Skills needed for a Line Cook role include cul...
1,1,Line Chef,- Prepared food for the kitchen and created sp...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,Skills needed for a Line Chef role include pro...
2,2,Executive Chef,- Promoted from rounds chef to sous chef in 20...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,Skills needed for the Executive Chef role incl...
3,3,Banquet Cook 2( Lead Cook),- Attended daily BEO meetings\n- Prepped and f...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,Skills needed for a Banquet Cook 2 (Lead Cook)...
4,4,Kitchen Supervisor,- Oversaw the am shift\n- Part of a renovation...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,Skills needed for a Kitchen Supervisor role in...

In [69]:
df_aug.iloc[1,-1]

'A Line Chef needs strong cooking skills, the ability to work efficiently in a fast-paced kitchen environment, and good communication skills to coordinate with other kitchen staff.'

In [70]:
df_aug_desc.iloc[1,-1]

'Skills needed for a Line Chef role include proficiency in cooking techniques, ability to work efficiently under pressure, strong attention to detail, leadership skills to train new cooks, and a thorough understanding of food preparation and recipe development.'

In [73]:
ind = 0

print(f'Aug: {df_aug.iloc[ind,-1]}')
print(f'AugDesc: {df_aug_desc.iloc[ind,-1]}')

Aug: A Line Cook needs to have strong culinary skills, including knife skills, cooking techniques, and knowledge of food safety protocols. They should also be able to work efficiently in a fast-paced kitchen environment and collaborate well with the rest of the kitchen team.
AugDesc: Skills needed for a Line Cook role include culinary techniques, food preparation, attention to detail in cleaning, and effective communication in a high-pressure kitchen setting.

In [74]:
df_recent.head()

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id,skill_brief
0,7930,Controller,Managed the financial health of a provider of ...,financial controller,Financial controllers handle all tasks related...,http://data.europa.eu/esco/occupation/5e5b1b61...,7930,Skills needed for the Controller role include ...
1,7931,Office Assistant,"Greeted persons entering establishment, determ...",administrative assistant,Administrative assistants provide administrati...,http://data.europa.eu/esco/occupation/044d78cc...,7931,Skills needed for an Office Assistant role inc...
2,7932,Software Engineer,- Designed and developed an application to mig...,software developer,Software developers implement or program all k...,http://data.europa.eu/esco/occupation/f2b15a0e...,7932,Skills needed for a Software Engineer role inc...
3,7933,Software Engineer,Worked at Star Media and DPS. Developed video ...,software developer,Software developers implement or program all k...,http://data.europa.eu/esco/occupation/f2b15a0e...,7933,Skills needed for a Software Engineer in this ...
4,7934,History Teacher,Fifth grade social studies teacher at Thunderb...,secondary school teacher,Secondary school teachers provide education to...,http://data.europa.eu/esco/occupation/5efb2c08...,7934,Skills needed for a History Teacher role inclu...

In [77]:
df_recent = df_recent[['job_id', 'raw_title', 'raw_description', 'esco_title',
       'esco_description', 'esco_id', 'skill_brief']]

In [75]:
df_aug_desc.head()

,job_id,raw_title,raw_description,esco_title,esco_description,esco_id,skill_brief
0,0,Line Cook,- Prepped food for the line and cooked appetiz...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,Skills needed for a Line Cook role include cul...
1,1,Line Chef,- Prepared food for the kitchen and created sp...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,Skills needed for a Line Chef role include pro...
2,2,Executive Chef,- Promoted from rounds chef to sous chef in 20...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,Skills needed for the Executive Chef role incl...
3,3,Banquet Cook 2( Lead Cook),- Attended daily BEO meetings\n- Prepped and f...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,Skills needed for a Banquet Cook 2 (Lead Cook)...
4,4,Kitchen Supervisor,- Oversaw the am shift\n- Part of a renovation...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,Skills needed for a Kitchen Supervisor role in...

In [78]:
df_recent.head()

,job_id,raw_title,raw_description,esco_title,esco_description,esco_id,skill_brief
0,7930,Controller,Managed the financial health of a provider of ...,financial controller,Financial controllers handle all tasks related...,http://data.europa.eu/esco/occupation/5e5b1b61...,Skills needed for the Controller role include ...
1,7931,Office Assistant,"Greeted persons entering establishment, determ...",administrative assistant,Administrative assistants provide administrati...,http://data.europa.eu/esco/occupation/044d78cc...,Skills needed for an Office Assistant role inc...
2,7932,Software Engineer,- Designed and developed an application to mig...,software developer,Software developers implement or program all k...,http://data.europa.eu/esco/occupation/f2b15a0e...,Skills needed for a Software Engineer role inc...
3,7933,Software Engineer,Worked at Star Media and DPS. Developed video ...,software developer,Software developers implement or program all k...,http://data.europa.eu/esco/occupation/f2b15a0e...,Skills needed for a Software Engineer in this ...
4,7934,History Teacher,Fifth grade social studies teacher at Thunderb...,secondary school teacher,Secondary school teachers provide education to...,http://data.europa.eu/esco/occupation/5efb2c08...,Skills needed for a History Teacher role inclu...

In [80]:
df_aug_desc_new = pd.concat([df_aug_desc, df_recent])

In [83]:
merged.rename(
    columns={
        'esco_id_y': 'esco_id',
        'esco_title_y': 'esco_title',
        'esco_description_y': 'esco_description',
        'raw_title_y': 'raw_title',
        'raw_description_y': 'raw_description'
    }
)[[ 'raw_title', 'raw_description', 'esco_title',
       'esco_description', 'esco_id', 'new_job_id']].rename(columns={'new_job_id':'job_id'}).merge(df_aug_desc_new[['job_id', 'skill_brief']]).to_csv('../data/processed/augmentation/augmented_decorte_occupations_with_desc_2.csv')

In [1]:
merged.rename(
    columns={
        'esco_id_y': 'esco_id',
        'esco_title_y': 'esco_title',
        'esco_description_y': 'esco_description',
        'raw_title_y': 'raw_title',
        'raw_description_y': 'raw_description'
    }
)[[ 'raw_title', 'raw_description', 'esco_title',
       'esco_description', 'esco_id', 'new_job_id']].rename(columns={'new_job_id':'job_id'})

NameError: name 'merged' is not defined

In [1]:
import pandas as pd

df_new = pd.read_csv('../data/processed/augmentation/augmented_decorte_occupations_with_desc_2.csv')

In [2]:
df_new.head()

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id,skill_brief
0,0,Line Cook,- Prepped food for the line and cooked appetiz...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,0,Skills needed for a Line Cook role include cul...
1,1,Line Chef,- Prepared food for the kitchen and created sp...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,1,Skills needed for a Line Chef role include pro...
2,2,Executive Chef,- Promoted from rounds chef to sous chef in 20...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...,2,Skills needed for the Executive Chef role incl...
3,3,Banquet Cook 2( Lead Cook),- Attended daily BEO meetings\n- Prepped and f...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...,3,Skills needed for a Banquet Cook 2 (Lead Cook)...
4,4,Kitchen Supervisor,- Oversaw the am shift\n- Part of a renovation...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...,4,Skills needed for a Kitchen Supervisor role in...

In [3]:
df_new.shape

(9885, 8)

In [5]:
df_new.drop(columns=['Unnamed: 0']).to_csv('../data/title_pairs_desc//decorte_master_2.csv')

In [7]:
df_new.query('esco_id == "http://data.europa.eu/esco/occupation/f4525ed8-54eb-4a3b-90db-55cc01b0d9fd"')

,Unnamed: 0,raw_title,raw_description,esco_title,esco_description,esco_id,job_id,skill_brief
214,214,Med Tech,Promoted continuity of care by accurately and ...,care home worker,Care home workers provide domiciliary services...,http://data.europa.eu/esco/occupation/f4525ed8...,214,Skills needed for a Med Tech role include stro...
5419,5419,Home Healthcare Provider,"Provided home healthcare services, including a...",care home worker,Care home workers provide domiciliary services...,http://data.europa.eu/esco/occupation/f4525ed8...,5419,Skills needed for a Home Healthcare Provider r...
5476,5476,Private Duty Home Healthcare Aide,Supported healthy nutrition by cooking meals a...,care home worker,Care home workers provide domiciliary services...,http://data.europa.eu/esco/occupation/f4525ed8...,5476,Skills needed for a Private Duty Home Healthca...
5500,5500,Healthcare Provider,"Through Manna, I provided care for a mentally ...",care home worker,Care home workers provide domiciliary services...,http://data.europa.eu/esco/occupation/f4525ed8...,5500,Skills needed for a Healthcare Provider role i...
6464,6464,Caregiver,"- Assessed the need for, ordered, obtained, an...",care home worker,Care home workers provide domiciliary services...,http://data.europa.eu/esco/occupation/f4525ed8...,6464,Skills needed for a Caregiver role include str...
6787,6787,Stay at home mom,Took a break from work to focus on being a sta...,care home worker,Care home workers provide domiciliary services...,http://data.europa.eu/esco/occupation/f4525ed8...,6787,Skills needed for the role of a stay at home m...
7944,7944,Healthcare Provider,Provided healthcare for at-home patients.,care home worker,Care home workers provide domiciliary services...,http://data.europa.eu/esco/occupation/f4525ed8...,7944,Skills needed for a Healthcare Provider includ...

In [1]:
import pandas as pd

df = pd.read_csv('/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/esco_datasets/occupationSkillRelations_en.csv')

In [2]:
df.head()

,occupationUri,relationType,skillType,skillUri
0,http://data.europa.eu/esco/occupation/00030d09...,essential,knowledge,http://data.europa.eu/esco/skill/fed5b267-73fa...
1,http://data.europa.eu/esco/occupation/00030d09...,essential,skill/competence,http://data.europa.eu/esco/skill/05bc7677-5a64...
2,http://data.europa.eu/esco/occupation/00030d09...,essential,skill/competence,http://data.europa.eu/esco/skill/271a36a0-bc7a...
3,http://data.europa.eu/esco/occupation/00030d09...,essential,skill/competence,http://data.europa.eu/esco/skill/47ed1d37-971b...
4,http://data.europa.eu/esco/occupation/00030d09...,essential,skill/competence,http://data.europa.eu/esco/skill/591dd514-735b...

In [3]:
import numpy as np

# 'occupationUri' = occupation, 'skillUri' = skill
# Calculate the IDF (Inverse Document Frequency) for each skill (skillUri) according to: 
# idf(skill) = log(N / df), where N = total number of unique occupations, 
# df = number of unique occupations that have this skill

N = df['occupationUri'].nunique()
skill_df = df.groupby('skillUri')['occupationUri'].nunique().reset_index(name='occ_count')
skill_df['idf'] = np.log(N / skill_df['occ_count'])

skill_df.head()

                                            skillUri  occ_count       idf
0  http://data.europa.eu/esco/skill/0005c151-5b5a...          4  6.632989
1  http://data.europa.eu/esco/skill/00064735-8fad...          1  8.019284
2  http://data.europa.eu/esco/skill/000709ed-2be5...         30  4.618086
3  http://data.europa.eu/esco/skill/0007bdc2-dd15...         11  5.621389
4  http://data.europa.eu/esco/skill/00090cc1-1f27...          2  7.326137

In [1]:
import pandas as pd

df_1 = pd.read_csv(r'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/processed/augmentation/augmented_esco_occupations_with_expanded_alts.csv')
df_2 = pd.read_csv(r'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/processed/augmentation/augmented_esco_occupations_expanded.csv')
df_3 = pd.read_csv(r'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/processed/augmentation/augmented_esco_occupations.csv')

In [2]:
df_1.shape

(33440, 5)

In [3]:
df_2.shape

(30401, 8)

In [4]:
df_3.shape

(3039, 2)

In [1]:
# additional task here, you can skip
import pandas as pd

df_master_2 = pd.read_csv(r'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/decorte_master_3.csv')

In [3]:
df_master_2.split.value_counts()

split
train    7882
test     1046
val       957
Name: count, dtype: int64

In [4]:
6905 + 1022

7927

In [5]:
6905 + 1022 + 821

8748