In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
df = pd.read_csv(r'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/results/cpp/experiment_results.csv')

In [46]:
df.columns

Index(['timestamp', 'run_name', 'architecture', 'text_history',
       'text_description', 'skill_text', 'skill_description', 'structured',
       'text_encoder', 'skill_encoder', 'pooling_strategy', 'last_job_only',
       'batch_size', 'max_epochs', 'patience', 'final_epochs', 'lr',
       'hidden_dim', 'n_layers', 'dropout', 'use_modality_weights', 'test_MRR',
       'test_R@1', 'test_R@5', 'test_R@10', 'test_R@20', 'test_clean_MRR',
       'test_clean_R@1', 'test_clean_R@5', 'test_clean_R@10',
       'test_clean_R@20', 'optimizer', 'optimizer_details'],
      dtype='object')

In [47]:
df.query('skill_text == True').sort_values('test_MRR')[['timestamp', 'run_name', 'test_MRR', 'test_R@10']]

,timestamp,run_name,test_MRR,test_R@10
42,2026-01-24 16:50:11,cpp_enhanced,0.006434434004116096,0.007214
12,2026-01-13 01:15:46,job_titles_skills_pjmath,0.2209799994272913,0.378468
13,2026-01-13 01:19:58,job_titles_skills_pjmath_adv,0.22318226432850743,0.387902
11,2026-01-02 01:18:56,job_with_skills_desc_adv,0.2607014731692131,0.418979
31,2026-01-24 00:22:19,job_titles_skills_mpnet_adv_weighted_idf_logpo...,0.261028135848823,0.418424
30,2026-01-24 00:17:48,job_titles_skills_mpnet_adv,0.261028135848823,0.418424
10,2026-01-02 01:11:18,job_with_skills_desc,0.2620127331090869,0.416759
14,2026-01-13 01:26:47,job_titles_skills_pjmath_desc,0.2627710440703393,0.417869
23,2026-01-23 23:32:53,job_titles_skills_pjmath_desc,0.2627932330472926,0.417869
46,2026-01-24 17:26:15,job_titles_skills_pjmath_desc_weighted_idf_log...,0.26324125586128755,0.419534
15,2026-01-13 01:30:24,job_titles_skills_pjmath_adv_desc,0.2634682977139767,0.424528
24,2026-01-23 23:37:29,job_titles_skills_pjmath_desc_adv,0.26352886744592197,0.424528
27,2026-01-23 23:55:11,job_titles_skills_pjmath_adv_desc_weighted_idf...,0.26363057432617565,0.425083
26,2026-01-23 23:51:14,job_titles_skills_pjmath_adv_desc_weighted_mean,0.26363057432617565,0.425083
25,2026-01-23 23:46:03,job_titles_skills_pjmath_adv_desc_weighted_idf,0.26363057432617565,0.425083
17,2026-01-13 01:53:28,job_titles_skills_pjmath_adv_desc_weighted_idf...,0.2636308062657623,0.425083
16,2026-01-13 01:43:39,job_titles_skills_pjmath_adv_desc_weighted_idf,0.2636308062657623,0.425083
47,2026-01-24 17:27:33,job_titles_skills_pjmath_desc_weighted_idf_log...,0.26364433312293656,0.418424
28,2026-01-24 00:00:54,job_titles_skills_mpnet,0.264107854877598,0.417869
29,2026-01-24 00:15:09,job_titles_skills_mpnet_adv,0.264107854877598,0.417869
50,2026-01-24 17:34:03,job_titles_skills_pjmath_desc_weighted_idf_adv...,0.2641616893429805,0.423418
41,2026-01-24 03:20:06,job_titles_skills_gte_desc_weighted_idf_logpoo...,0.26508435147434867,0.427303
40,2026-01-24 03:18:25,job_titles_skills_gte_desc_weighted_idf_logpoo...,0.2656114431262138,0.426193
39,2026-01-24 03:15:42,job_titles_skills_mpnet_desc_weighted_idf_logp...,0.2656114431262138,0.426193
49,2026-01-24 17:32:57,job_titles_skills_pjmath_desc_weighted_idf_adv...,0.26563241005696114,0.417869
52,2026-01-24 17:45:25,job_titles_skills_gte_ft_desc_weighted_idf_log...,0.26566508643354564,0.423418
44,2026-01-24 17:18:28,job_titles_skills_mpnet_desc_weighted_idf_logp...,0.26593966402044644,0.425083
32,2026-01-24 02:56:10,job_titles_skills_pjmath_desc,0.26613014910298993,0.426748
51,2026-01-24 17:43:17,job_titles_skills_mpnet_ft_desc_weighted_idf_l...,0.2661760889278908,0.425638
33,2026-01-24 02:57:41,job_titles_skills_pjmath_desc_weighted_mean,0.2669607937443421,0.426193
43,2026-01-24 17:16:02,job_titles_skills_pjmath_desc_weighted_idf_log...,0.2674301611420352,0.425638
38,2026-01-24 03:09:19,job_titles_skills_pjmath_desc_weighted_idf_log...,0.2674301611420352,0.425638
35,2026-01-24 03:02:20,job_titles_skills_pjmath_desc_adv,0.2680768714785701,0.428968
34,2026-01-24 02:59:22,job_titles_skills_pjmath_desc_weighted_idf,0.2682978816511156,0.426193
45,2026-01-24 17:24:56,job_titles_skills_pjmath_desc_weighted_idf_log...,0.26846014752776903,0.424528
48,2026-01-24 17:31:42,job_titles_skills_pjmath_desc_weighted_idf_adv...,0.2688709117121145,0.423418
36,2026-01-24 03:04:20,job_titles_skills_pjmath_desc_weighted_mean_adv,0.26906014761951347,0.426748
37,2026-01-24 03:06:02,job_titles_skills_pjmath_desc_weighted_idf_adv,0.26968005150942537,0.425638

In [48]:
df.query('skill_text == True').sort_values('test_clean_MRR')[['timestamp', 'run_name', 'test_clean_MRR', 'test_R@10']]

,timestamp,run_name,test_clean_MRR,test_R@10
12,2026-01-13 01:15:46,job_titles_skills_pjmath,0.242374,0.378468
13,2026-01-13 01:19:58,job_titles_skills_pjmath_adv,0.244787,0.387902
10,2026-01-02 01:11:18,job_with_skills_desc,0.270466,0.416759
47,2026-01-24 17:27:33,job_titles_skills_pjmath_desc_weighted_idf_log...,0.270724,0.418424
31,2026-01-24 00:22:19,job_titles_skills_mpnet_adv_weighted_idf_logpo...,0.270867,0.418424
30,2026-01-24 00:17:48,job_titles_skills_mpnet_adv,0.270867,0.418424
11,2026-01-02 01:18:56,job_with_skills_desc_adv,0.273900,0.418979
23,2026-01-23 23:32:53,job_titles_skills_pjmath_desc,0.275300,0.417869
14,2026-01-13 01:26:47,job_titles_skills_pjmath_desc,0.275301,0.417869
28,2026-01-24 00:00:54,job_titles_skills_mpnet,0.275663,0.417869
29,2026-01-24 00:15:09,job_titles_skills_mpnet_adv,0.275663,0.417869
41,2026-01-24 03:20:06,job_titles_skills_gte_desc_weighted_idf_logpoo...,0.276191,0.427303
51,2026-01-24 17:43:17,job_titles_skills_mpnet_ft_desc_weighted_idf_l...,0.276650,0.425638
52,2026-01-24 17:45:25,job_titles_skills_gte_ft_desc_weighted_idf_log...,0.277106,0.423418
40,2026-01-24 03:18:25,job_titles_skills_gte_desc_weighted_idf_logpoo...,0.277143,0.426193
39,2026-01-24 03:15:42,job_titles_skills_mpnet_desc_weighted_idf_logp...,0.277143,0.426193
50,2026-01-24 17:34:03,job_titles_skills_pjmath_desc_weighted_idf_adv...,0.277318,0.423418
33,2026-01-24 02:57:41,job_titles_skills_pjmath_desc_weighted_mean,0.277767,0.426193
26,2026-01-23 23:51:14,job_titles_skills_pjmath_adv_desc_weighted_mean,0.278131,0.425083
25,2026-01-23 23:46:03,job_titles_skills_pjmath_adv_desc_weighted_idf,0.278131,0.425083
27,2026-01-23 23:55:11,job_titles_skills_pjmath_adv_desc_weighted_idf...,0.278131,0.425083
15,2026-01-13 01:30:24,job_titles_skills_pjmath_adv_desc,0.278135,0.424528
24,2026-01-23 23:37:29,job_titles_skills_pjmath_desc_adv,0.278172,0.424528
16,2026-01-13 01:43:39,job_titles_skills_pjmath_adv_desc_weighted_idf,0.278188,0.425083
17,2026-01-13 01:53:28,job_titles_skills_pjmath_adv_desc_weighted_idf...,0.278188,0.425083
44,2026-01-24 17:18:28,job_titles_skills_mpnet_desc_weighted_idf_logp...,0.278801,0.425083
34,2026-01-24 02:59:22,job_titles_skills_pjmath_desc_weighted_idf,0.279695,0.426193
48,2026-01-24 17:31:42,job_titles_skills_pjmath_desc_weighted_idf_adv...,0.280364,0.423418
32,2026-01-24 02:56:10,job_titles_skills_pjmath_desc,0.281044,0.426748
46,2026-01-24 17:26:15,job_titles_skills_pjmath_desc_weighted_idf_log...,0.281078,0.419534
35,2026-01-24 03:02:20,job_titles_skills_pjmath_desc_adv,0.282435,0.428968
36,2026-01-24 03:04:20,job_titles_skills_pjmath_desc_weighted_mean_adv,0.282459,0.426748
37,2026-01-24 03:06:02,job_titles_skills_pjmath_desc_weighted_idf_adv,0.283293,0.425638
49,2026-01-24 17:32:57,job_titles_skills_pjmath_desc_weighted_idf_adv...,0.284461,0.417869
45,2026-01-24 17:24:56,job_titles_skills_pjmath_desc_weighted_idf_log...,0.285099,0.424528
38,2026-01-24 03:09:19,job_titles_skills_pjmath_desc_weighted_idf_log...,0.286599,0.425638
43,2026-01-24 17:16:02,job_titles_skills_pjmath_desc_weighted_idf_log...,0.286599,0.425638
42,2026-01-24 16:50:11,cpp_enhanced,NaN,0.007214

In [56]:
df.query('skill_text == True').sort_values('test_clean_MRR')[['timestamp', 'run_name', 'test_clean_MRR', 'test_R@10']].tail(5).run_name.unique()

array(['job_titles_skills_pjmath_desc_weighted_idf_adv_thres0_7',
       'job_titles_skills_pjmath_desc_weighted_idf_logpool_adv_thres0_5',
       'job_titles_skills_pjmath_desc_weighted_idf_logpool_adv',
       'job_titles_skills_pjmath_desc_weighted_idf_logpool_adv_2',
       'cpp_enhanced'], dtype=object)

In [57]:
df.query('skill_text == True').sort_values('test_MRR')[['timestamp', 'run_name', 'test_MRR', 'test_R@10']].tail(5).run_name.unique()

array(['job_titles_skills_pjmath_desc_weighted_idf',
       'job_titles_skills_pjmath_desc_weighted_idf_logpool_adv_thres0_5',
       'job_titles_skills_pjmath_desc_weighted_idf_adv_thres0_5',
       'job_titles_skills_pjmath_desc_weighted_mean_adv',
       'job_titles_skills_pjmath_desc_weighted_idf_adv'], dtype=object)

In [ ]:
df = df.query('timestamp >= "2026-01-23"')

,timestamp,run_name,architecture,text_history,text_description,skill_text,skill_description,structured,text_encoder,skill_encoder,...,test_R@5,test_R@10,test_R@20,test_clean_MRR,test_clean_R@1,test_clean_R@5,test_clean_R@10,test_clean_R@20,optimizer,optimizer_details
19,2026-01-23 15:29:46,job_titles_desc,SimpleConcat,True,NaN,False,NaN,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.349612,0.420089,0.498335,0.276205,0.189427,0.374449,0.414097,0.493392,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
20,2026-01-23 15:36:18,job_titles,SimpleConcat,True,False,False,NaN,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.291343,0.376249,0.463374,0.248928,0.162996,0.348018,0.414097,0.488987,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
21,2026-01-23 17:48:23,job_title_only,SimpleConcat,True,False,False,NaN,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.294118,0.363485,0.450055,0.238445,0.158590,0.334802,0.396476,0.466960,adam,"Adam(lr=0.000314, weight_decay=0.000273)"
22,2026-01-23 18:03:39,job_title_desc,SimpleConcat,True,True,False,NaN,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.356271,0.418979,0.481132,0.275688,0.193833,0.383260,0.409692,0.458150,adam,"Adam(lr=0.000249, weight_decay=0.000135)"
23,2026-01-23 23:32:53,job_titles_skills_pjmath_desc,SimpleConcat,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.350166,0.417869,0.496115,0.275300,0.198238,0.370044,0.418502,0.502203,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
24,2026-01-23 23:37:29,job_titles_skills_pjmath_desc_adv,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.352386,0.424528,0.497225,0.278172,0.193833,0.370044,0.431718,0.493392,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
25,2026-01-23 23:46:03,job_titles_skills_pjmath_adv_desc_weighted_idf,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.352386,0.425083,0.497225,0.278131,0.193833,0.370044,0.431718,0.493392,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
26,2026-01-23 23:51:14,job_titles_skills_pjmath_adv_desc_weighted_mean,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.352386,0.425083,0.497225,0.278131,0.193833,0.370044,0.431718,0.493392,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
27,2026-01-23 23:55:11,job_titles_skills_pjmath_adv_desc_weighted_idf...,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.352386,0.425083,0.497225,0.278131,0.193833,0.370044,0.431718,0.493392,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
28,2026-01-24 00:00:54,job_titles_skills_mpnet,SimpleConcat,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.344062,0.417869,0.493896,0.275663,0.193833,0.378855,0.431718,0.497797,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
29,2026-01-24 00:15:09,job_titles_skills_mpnet_adv,SimpleConcat,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.344062,0.417869,0.493896,0.275663,0.193833,0.378855,0.431718,0.497797,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
30,2026-01-24 00:17:48,job_titles_skills_mpnet_adv,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.341842,0.418424,0.498890,0.270867,0.185022,0.374449,0.422907,0.493392,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
31,2026-01-24 00:22:19,job_titles_skills_mpnet_adv_weighted_idf_logpo...,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.341842,0.418424,0.498890,0.270867,0.185022,0.374449,0.422907,0.493392,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
32,2026-01-24 02:56:10,job_titles_skills_pjmath_desc,SimpleConcat,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.347947,0.426748,0.500000,0.281044,0.198238,0.374449,0.436123,0.493392,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
33,2026-01-24 02:57:41,job_titles_skills_pjmath_desc_weighted_mean,SimpleConcat,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.350166,0.426193,0.499445,0.277767,0.189427,0.374449,0.440529,0.488987,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
34,2026-01-24 02:59:22,job_titles_skills_pjmath_desc_weighted_idf,SimpleConcat,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.348502,0.426193,0.499445,0.279695,0.193833,0.370044,0.440529,0.488987,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
35,2026-01-24 03:02:20,job_titles_skills_pjmath_desc_adv,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.354051,0.428968,0.504440,0.282435,0.198238,0.396476,0.431718,0.488987,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
36,2026-01-24 03:04:20,job_titles_skills_pjmath_desc_weighted_mean_adv,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.355161,0.426748,0.506104,0.282459,0.198238,0.396476,0.431718,0.484581,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
37,2026-01-24 03:06:02,job_titles_skills_pjmath_desc_weighted_idf_adv,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.355716,0.425638,0.507769,0.283293,0.198238,0.396476,0.427313,0.488987,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
38,2026-01-24 03:09:19,job_titles_skills_pjmath_desc_weighted_idf_log...,MultiModal,True,True,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.352941,0.425638,0.503885,0.286599,0.207048,0.392070,0.431718,0.488987,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
39,2026-01-24 03:13:16,job_titles_skills_mpnet_desc_weighted_idf_logp...,MultiModal,True,True,True,True,False,ElenaSenger/career-path-representation-mpnet-d...,/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95ki...,...,0.352941,0.425638,0.503885,0.286599,0.207048,0.392070,0.431718,0.488987,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
40,2026-01-24 03:15:42,job_titles_skills_mpnet_desc_weighted_idf_logp...,MultiModal,True,True,True,True,False,ElenaSenger/career-path-representation-mpnet-d...,/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95ki...,...,0.346282,0.426193,0.499445,0.277143,0.189427,0.378855,0.431718,0.497797,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
41,2026-01-24 03:18:25,job_titles_skills_gte_desc_weighted_idf_logpoo...,MultiModal,True,True,True,True,False,ElenaSenger/career-path-representation-mpnet-d...,/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95ki...,...,0.346282,0.426193,0.499445,0.277143,0.189427,0.378855,0.431718,0.497797,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
42,2026-01-24 03:20:06,job_titles_skills_gte_desc_weighted_idf_logpoo...,MultiModal,True,True,True,True,False,ElenaSenger/career-path-representation-mpnet-d...,/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95ki...,...,0.347392,0.427303,0.500555,0.276191,0.189427,0.378855,0.431718,0.488987,adam,"Adam(lr=0.000020, weight_decay=0.000000)"
43,2026-01-24 16:50:11,cpp_enhanced,SimpleConcat,True,False,True,False,False,ElenaSenger/career-path-representation-mpnet-d...,ElenaSenger/career-path-representation-mpnet-d...,...,0.002775,0.007214,0.021643,NaN,NaN,NaN,NaN,NaN,adam,"Adam(lr=0.000020, weight_decay=0.000000)"

In [3]:
import pickle

text_path = '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95kix2/results/cpp/decorte/job_title_desc/scores/test_scores_text.pkl'
hybrid_path = '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95kix2/results/cpp/decorte_static/job_titles_skills_pjmath_desc_weighted_idf_logpool_adv_2/scores/test_scores_text.pkl'
skill_path = '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ra95kix2/results/cpp/decorte/skills_only_pjmath_desc_weighted_idf_logpool_adv/scores/test_scores_text.pkl'

def load_targets(path):
    with open(path, "rb") as f:
        d = pickle.load(f)
    # assume compatible file structure: check 'target_labels' or fallback
    if 'target_labels' in d:
        return set(d['target_labels'])
    elif 'target_label' in d:
        return set(d['target_label'])
    elif hasattr(d, 'target_labels'):
        return set(d.target_labels)
    else:
        raise ValueError(f"No target_labels key in {path}")

text_targets = load_targets(text_path)
hybrid_targets = load_targets(hybrid_path)
skill_targets = load_targets(skill_path)

print("Number of unique labels:")
print("Text:", len(text_targets))
print("Hybrid:", len(hybrid_targets))
print("Skill:", len(skill_targets))

if text_targets == hybrid_targets == skill_targets:
    print("All have identical target label pools.")
else:
    print("Target label pools differ!")
    print("Only in text:", text_targets - hybrid_targets - skill_targets)
    print("Only in hybrid:", hybrid_targets - text_targets - skill_targets)
    print("Only in skill:", skill_targets - text_targets - hybrid_targets)
    print("Intersection size:", len(text_targets & hybrid_targets & skill_targets))
    print("Difference (text vs hybrid):", len(text_targets.symmetric_difference(hybrid_targets)))
    print("Difference (hybrid vs skill):", len(hybrid_targets.symmetric_difference(skill_targets)))
    print("Difference (text vs skill):", len(text_targets.symmetric_difference(skill_targets)))

Number of unique labels:
Text: 1022
Hybrid: 1022
Skill: 1022
All have identical target label pools.

In [2]:
# Show a few sample targets from each method

print("Sample targets from Text (first 10):", list(text_targets)[:10])
print("Sample targets from Skill (first 10):", list(skill_targets)[:10])
print("Sample targets from Hybrid (first 10):", list(hybrid_targets)[:10])

Sample targets from Text (first 10): ['esco role: case administrator \n description: Case administrators supervise the progress of criminal and civil cases from the point of opening to closing. They review the case files and case progression to ensure proceedings occur compliant with legislation. They also ensure the proceedings occur in a timely manner and that everything has been concluded before closing cases.', 'esco role: vocational teacher \n description: Vocational teachers instruct students in their specialised field of study, which is predominantly practical in nature. They provide theoretical instruction in service of the practical skills and techniques that the students must subsequently master in the specialised vocation of their choice and aid in the development of the according attitudes and values. Vocational teachers monitor the students progress, assist individually when necessary, and evaluate their knowledge and performance on the subject through assignments, tests and examinations.', 'esco role: survey enumerator \n description: Survey enumerators perform interviews and fill in forms in order to collect the data provided by interviewees. They can collect information by phone, mail, personal visits or on the street. They conduct and help the interviewees administer the information that the interviewer is interested in having, usually related to demographic information for governmental statistical purposes.', 'esco role: office clerk \n description: Office clerks are responsible for performing clerical and administrative duties in an office setting and support of business operations within a department. They assist all the administrative staff, secretaries, and assistants by sorting mail, filing forms and documents, answering phones, greeting clients and scheduling meetings.', "esco role: financial planner \n description: Financial planners assist people dealing with various personal financial issues. They are specialised in financial planning, such as retirement planning, investment planning, risk management and insurance planning, and tax planning. They advise a strategy tailored to the client's needs. They ensure the accuracy of bank and other financial records while maintaining a customer-orientated approach and following ethical standards.", 'esco role: musical conductor \n description: Musical conductors lead ensembles of musicians directing them during rehearsals, recording sessions and live performances and helping them attaining their best performance. They can work with a variety of ensembles such as choirs and orchestras. Musical conductors adjust the tempo (speed), rhythm, dynamics (loud or soft) and articulation (smooth or detached) of the music using gestures and sometimes dancing to motivate the musicians to play according to the music sheet.', 'esco role: mail clerk \n description: Mail clerks perform mail handling, sorting, recording and other duties in connection with mail services from post offices or related organisations. They keep records of the incoming and outgoing packages and letters in the establishment.', 'esco role: art director \n description: Art directors shape the visual layout of a concept. They create innovative designs, develop artistic projects \xa0and manage the cooperation between all aspects involved. Art directors may perform creative work in theatre, marketing, advertising, video and motion picture, fashion or online companies. They ensure that the work performed is visually appealing to audiences.', 'esco role: business manager \n description: Business managers are responsible for setting the objectives of the business unit of a company, creating a plan for the operations, and facilitating the achievement of the objectives and implementation of the plan together with employees of the segment and stakeholders. They keep an overview of the business, understand detailed information of the business unit and support the department, and make decisions based on the information at hand.', 'esco role: construction painting supervisor \n description: Construction painting supervisors plan, direct and oversee the work of the crew of painters assigned to a certain project or location. They supervise and evaluate the work of painters.']
Sample targets from Skill (first 10): ['public administration manager ', 'deputy head teacher ', 'architect ', 'middle office analyst ', 'police officer ', 'medical device engineer ', 'choreographer ', 'swimming facility attendant ', 'sales manager ', 'financial fraud examiner ']
Sample targets from Hybrid (first 10): ['esco role: case administrator \n description: Case administrators supervise the progress of criminal and civil cases from the point of opening to closing. They review the case files and case progression to ensure proceedings occur compliant with legislation. They also ensure the proceedings occur in a timely manner and that everything has been concluded before closing cases.', 'esco role: vocational teacher \n description: Vocational teachers instruct students in their specialised field of study, which is predominantly practical in nature. They provide theoretical instruction in service of the practical skills and techniques that the students must subsequently master in the specialised vocation of their choice and aid in the development of the according attitudes and values. Vocational teachers monitor the students progress, assist individually when necessary, and evaluate their knowledge and performance on the subject through assignments, tests and examinations.', 'esco role: survey enumerator \n description: Survey enumerators perform interviews and fill in forms in order to collect the data provided by interviewees. They can collect information by phone, mail, personal visits or on the street. They conduct and help the interviewees administer the information that the interviewer is interested in having, usually related to demographic information for governmental statistical purposes.', "esco role: financial planner \n description: Financial planners assist people dealing with various personal financial issues. They are specialised in financial planning, such as retirement planning, investment planning, risk management and insurance planning, and tax planning. They advise a strategy tailored to the client's needs. They ensure the accuracy of bank and other financial records while maintaining a customer-orientated approach and following ethical standards.", 'esco role: office clerk \n description: Office clerks are responsible for performing clerical and administrative duties in an office setting and support of business operations within a department. They assist all the administrative staff, secretaries, and assistants by sorting mail, filing forms and documents, answering phones, greeting clients and scheduling meetings.', 'esco role: musical conductor \n description: Musical conductors lead ensembles of musicians directing them during rehearsals, recording sessions and live performances and helping them attaining their best performance. They can work with a variety of ensembles such as choirs and orchestras. Musical conductors adjust the tempo (speed), rhythm, dynamics (loud or soft) and articulation (smooth or detached) of the music using gestures and sometimes dancing to motivate the musicians to play according to the music sheet.', 'esco role: mail clerk \n description: Mail clerks perform mail handling, sorting, recording and other duties in connection with mail services from post offices or related organisations. They keep records of the incoming and outgoing packages and letters in the establishment.', 'esco role: art director \n description: Art directors shape the visual layout of a concept. They create innovative designs, develop artistic projects \xa0and manage the cooperation between all aspects involved. Art directors may perform creative work in theatre, marketing, advertising, video and motion picture, fashion or online companies. They ensure that the work performed is visually appealing to audiences.', 'esco role: business manager \n description: Business managers are responsible for setting the objectives of the business unit of a company, creating a plan for the operations, and facilitating the achievement of the objectives and implementation of the plan together with employees of the segment and stakeholders. They keep an overview of the business, understand detailed information of the business unit and support the department, and make decisions based on the information at hand.', 'esco role: technical communicator \n description: Technical communicators prepare clear, concise and professional\xa0communication from product developers to users of the products such as online help, user manuals, white papers, specifications and industrial videos. For this, they analyse products, legal requirements, markets, customers and users. They develop information and media concepts, standards, structures and software tool support. They plan the content creation and media production processes, develop written, graphical, video or other contents, generate media output, release their information products and\xa0receive feedback from the users.']

In [4]:
with open(skill_path, "rb") as f:
        d = pickle.load(f)

In [5]:
d

{'scores': array([[ 0.04914309,  0.34235194,  0.02088643, ...,  0.16271047,
         -0.00059182,  0.08834528],
        [-0.0091578 ,  0.39084613,  0.13391298, ...,  0.11763944,
         -0.04408932,  0.02530464],
        [-0.0091578 ,  0.39084613,  0.13391298, ...,  0.11763944,
         -0.04408932,  0.02530464],
        ...,
        [ 0.01778377, -0.03739518, -0.01542022, ..., -0.06243482,
          0.30727845,  0.09776814],
        [ 0.08380534,  0.00533864, -0.00214798, ..., -0.05566553,
          0.32502395,  0.10121747],
        [ 0.08380534,  0.00533864, -0.00214798, ..., -0.05566553,
          0.32502395,  0.10121747]], shape=(1802, 1022), dtype=float32),
 'target_labels': ['esco role: credit analyst \n description: Credit analysts investigate credit applications from customers and evaluate if the applications comply with regulations and guidelines of the financial loan-granting institution. On the basis of credit analyses they advise financial institutions whether customers are loan worthy. They perform tasks such as collecting data on the loan applicant, aquire additional information from other departments or institutions and indicating what sort of agreements the financial institution should reach with the credit applicant. Credit analysts also follow up on the development of the credit portfolio of clients.',
  'esco role: housekeeping supervisor \n description: Housekeeping supervisors are in charge of supervising and coordinating the\xa0daily running of cleaning and housekeeping activities\xa0hospitality establishments.',
  'esco role: shoe and leather accessories shop manager \n description: Shoe and leather accessories shop managers assume responsibility for activities and staff in specialised shops.',
  "esco role: literature teacher at secondary school \n description: Literature teachers at secondary schools provide education to students, commonly children and young adults, in a secondary school setting. They are usually subject teachers, specialised and instructing in their own field of study, literature. They prepare lesson plans and materials, monitor the students' progress, assist individually when necessary, and evaluate the students' knowledge and performance on the subject of literature through assignments, tests and examinations.",
  'esco role: musician \n description: Musicians perform a vocal or musical part that can be recorded or played for an audience. They have know-how and practice of one or many instruments or using their voice. The musician can also write and transcribe music.',
  'esco role: labour relations officer \n description: Labour relations officers implement labour policy in an organisation, and advise trade unions on policies and negotiation. They handle disputes, and advise management on personnel policy as well as facilitate communication between trade unions and managerial staff.',
  'esco role: communications lecturer \n description: Communications lecturers are subject professors, teachers, or lecturers who instruct students who have obtained an upper secondary education diploma in their own specialised field of study, communications, which is predominantly academic in nature. They work with their\xa0university research assistants and university teaching assistants\xa0for the preparation of lectures and of exams, grading papers and exams and leading review and feedback sessions for the students. They also conduct academic research in their field of communications, publish their findings and liaise with other university colleagues.',
  'esco role: ict system analyst \n description: ICT system analysts specify the system needs to meet the end user requirements. They analyse system functions in order to define their goals or purposes and to discover operations and procedures for accomplishing them most efficiently. They also design new IT solutions to improve business efficiency and productivity, produce outline designs and estimate costs of new systems, specify the operations the system will perform, and the way data will be viewed by the end user. They present the design to the users and work closely with the users to implement the solution.',
  'esco role: aircraft assembler \n description: Aircraft assemblers use hand tools, power tools and other equipment such as CNC machines or robots to construct, fit and install prefabricated parts to manufacture fixed or rotary wing aircrafts and aircraft subassemblies such as flight controls, aircraft skins, rigging and other mechanical systems. They read and interpret blueprints. They operate control systems to determine functional performance of the assemblies and adjust accordingly.',
  'esco role: social work supervisor \n description: Social work supervisors manage social work cases by investigating alleged neglect or abuse cases. They make family dynamics assessment and provide assistance to sick people or with emotional or mental disorders. They train, assist, advise, evaluate and assign work to subordinate social workers making sure that all work is done according to the established policies, laws, procedures and priorities.',
  "esco role: chief technology officer \n description: Chief technology officers contribute to a company's technical vision and lead all aspects of technology development, according to its strategic direction and growth objectives. They match technology with business needs.",
  'esco role: digital games designer \n description: Digital games designers develop the layout, logic, concept and gameplay of a digital game. They focus on playfield design, specification writing, and entry of numeric properties that balance and tune the gameplay.',
  'esco role: accommodation manager \n description: Accommodation managers are in charge of managing the operations and overseeing the strategy for a hospitality establishment. They manage human resources, finances, marketing and operations through activities such as supervising the staff, keeping financial records and organising activities. ',
  'esco role: bulldozer operator \n description: Bulldozer operators operate a heavy vehicle to move earth, rubble or other material over the ground.',
  'esco role: animal feed nutritionist \n description: Animal feed nutritionists analyse the nutritional value of animal feeds in order to provide dietary advice to agricultural, manufacturing, zoological and public sector staff. They undertake research on nutritionally balanced food stuffs and maintain awareness of technical and scientific developments on the subject.',
  'esco role: electrician \n description: Electricians fit and repair electrical circuits and wiring systems. They also install and maintain electrical equipment and machinery. This work can be performed indoors as well as outdoors, in nearly every type of facility.',
  'esco role: administrative assistant \n description: Administrative assistants provide administrative and office support for supervisors. They perform a variety of tasks, such as answering telephone calls, receiving and directing visitors, ordering office supplies, maintaining the office facilities running smoothly, and ensuring that equipment and appliances work properly.',
  'esco role: fundraising assistant \n description: Fundraising assistants provide administrative support for fundraising managers. They target potential donators or sponsors by applying surveys. They process donations and grant payments, maintain electronic and paper filing systems for all grants and donations, acknowledge donations and write thank you letters and maintain fundraising records.',
  'esco role: instrumentation engineer \n description: Instrumentation engineers envision and design equipment used in manufacturing processes for controlling and monitoring various engineering processes remotely. They design equipment for the monitoring of production sites such as manufacturing systems, machinery uses and production processes.',
  'esco role: data warehouse designer \n description: Data warehouse designers are responsible for planning, connecting, designing, scheduling, and deploying data warehouse systems. They develop, monitor and maintain ETL processes, reporting applications and data warehouse design.',
  'esco role: digital games developer \n description: Digital games developers program, implement and document digital games. They implement technical standards in gameplay, graphics, sound and functionality.',
  'esco role: vehicle technician \n description: Vehicle technicians inspect, test and maintain vehicles, motorcycles, engine tune-ups and tyre replacements. They repair engine failures, lube replacements. Vehicle technicians replace vehicle components and evaluate warranty options. \n \n\xa0',
  'esco role: physical education teacher secondary school \n description: Physical education teachers at secondary schools provide education to\xa0students, commonly children and young adults, in a\xa0secondary school setting. They are usually subject teachers, specialised and instructing in their own field of study, physical education\xa0. They prepare lesson plans and materials, monitor the students’ progress, assist individually when necessary, and evaluate the students’ knowledge and performance on the subject of physical education\xa0through practical, usually physical, tests and examinations.',
  'esco role: motor vehicles specialised seller \n description: Motor vehicles specialised sellers\xa0sell cars and motors vehicles in specialised shops. \n \n\xa0',
  'esco role: curriculum administrator \n description: Curriculum administrators develop and improve the curricula of education institutions. They analyse the quality of existing curricula and work towards improvement. They communicate with education professionals to ensure an accurate analysis. They report on curriculum developments and perform administrative duties.',
  'esco role: writer \n description: Writers develop content for books. They write novels, poetry, short stories, comics and other forms of literature. These forms of writing can be fictional or non-fictional.',
  'esco role: fuel station manager \n description: Fuel station managers assume responsibility for activities and staff in a fuel station.',
  'esco role: eu funds manager \n description: EU funds managers administer EU funds and financial resources in public administrations. They are involved in the definition of investment priorities and are responsible for drafting the Operational Programs, liaising with national authorities for determining the programs ’objectives and priority axes. EU funds managers supervise projects financed through EU funds, monitoring their implementation and the results achieved and are involved in certification and auditing activities. They might also be responsible for managing the relations with the European institutions for issues related to state aids and the grant management.  ',
  'esco role: sport administrator \n description: Sport administrators act in a middle management role within sport organisations at all levels, in any sport or country in Europe (e.g. sport clubs, federations, and local authorities). They carry out organisational tasks across a wide range of functions in accordance with the strategy and policies set by management, boards of directors and committees. They play a crucial role in the overall delivery of sport and their work in sport organisations directly impact the unlocking of the potential of the sector in Europe towards health, social inclusion and economy.',
  'esco role: promotions demonstrator \n description: Promotions demonstrators proactively seek out and engage with new potential clients. They provide product specific advice and demonstrate promotional goods or services.',
  'esco role: medical practice manager \n description: Medical practice managers manage the day-to-day operations of a medical practice. They oversee the staff and business side of the practice.',
  'esco role: structural ironworker \n description: Structural ironworker in construction install iron elements into structures. They erect steel frameworks for buildings, bridges and other construction projects. They set metal rods, or rebar, to form reinforced concrete.',
  "esco role: agronomist \n description: Agronomists provide consulting services to companies, agricultural cooperatives,\xa0agronomical crop growers and horticultural crop growers\xa0on the cultivation of food crops. They study the science, technology and business related to growing plants. They examine crops and perform experiments in order to improve crop yields and farms' production. Agronomists also examine the most effective ways to harvest and cultivate plants.",
  'esco role: architectural drafter \n description: Architectural drafters make drawings of the specifications and ideas provided by architects. They draw architectural drawings using computer-aided equipment and software, or using conventional methods like paper and pen.',
  "esco role: further education principal \n description: Further education principals manage the day-to-day activities of a post-secondary education institute, such as technical institutes and other post-secondary schools. Further education principals make decisions concerning admissions and are responsible for meeting curriculum standards, which facilitate academic development for the students. They manage staff, the school's budget and programmes and oversee the communication between departments. They also ensure the school meets the national education requirements set by law.",
  'esco role: shop manager \n description: Shop managers are responsible for activities and staff in specialised shops.',
  'esco role: rooms division manager \n description: Rooms division managers are in charge of managing and coordinating a team of employees at front desk, reservations, housekeeping and maintenance departments.',
  'esco role: sports journalist \n description: Sports journalists research and write articles about sport events and athletes for newspapers, magazines, television and other media. They conduct interviews and attend events.',
  'esco role: wearing apparel patternmaker \n description: Wearing apparel patternmakers interpret design sketches and cut patterns for all kinds of wearing apparel using various handtools or industrial machines complying with customer requirements. They make samples and prototypes in order to produce series of patterns of wearing apparel in different sizes.',
  "esco role: care home worker \n description: Care home workers provide domiciliary services to vulnerable adults including frail elderly or disabled people who are living with physical impairment or convalescing, following a specific plan to provide day-to-day care to clients. They look after the physical and mental wellbeing of clients by providing them social care.\n\nThese services could be developed in residential homes, care homes or in the patient's home. In relation to this last case, they aim to improve patients' lives in the community and assure patients can live safely and independently in their own home.",
  'esco role: financial markets back office administrator \n description: Financial markets back office administrators perform administrative tasks for all the transactions registered in the trading room. They process transactions involving securities, derivatives, foreign exchange, commodities, and manage the clearing and settling of trades.',
  'esco role: advertising media buyer \n description: Advertising media buyers purchase, on behalf of their clients, advertising space in the print, broadcast and online media. They analyse the effectiveness and appropriateness of the different channels depending on the good or service, providing advice for the decision-making. They try to negotiate the best price, without compromising the quality of the advertisements. They support the development and implementation of marketing and advertising plans through the most suited media outlet.',
  'esco role: rail logistics coordinator \n description: Rail logistics coordinators manage\xa0shipments by rail including or excluding other transport modes. They coordinate the timely allocation of transport means and equipment and\xa0ensure a timely delivery. They design and\xa0maintain efficient supply chains for\xa0clients and shippers.',
  'esco role: head pastry chef \n description: Head pastry chefs manage pastry staff and ensure the\xa0preparation, cooking and presentation of desserts, sweet products and pastry products.\xa0',
  "esco role: special educational needs teacher \n description: Special educational needs teachers work with and teach children, young people, and adults with an intellectual or physical disability. They use a range of specialised concepts, strategies and tools to optimise learners' communication, mobility, autonomy, and social integration. They select teaching methods and support resources to enable individual learners to maximise their potential for independent living.",
  'esco role: railway station manager \n description: Railway station managers are in charge of\xa0organising\xa0tasks linked to the operation of train stations. Their tasks cover\xa0the organisation of the maintenance and repairment works for buildings and interior equipment. They care for the comfort, service, safety and security of passengers, other clients\xa0and\xa0the commercial use of buildings. Depending on the size of the station, the number of staff that railway station managers are directly responsible for can be high.',
  'esco role: hospital social worker \n description: Hospital social workers provide counselling to patients and their families helping them to better cope with the illness, the emotions surrounding diagnosis, and with social and financial problems. They work in cooperation with doctors, nurses and other health professionals sensitising them on the emotional aspects of a patient. They act as link between patients and medical staff. Hospital social workers also support the patients and their families with the discharge from the hospital.',
  'esco role: wire harness assembler \n description: Wire harness assemblers bind wires or cables to form wire harnesses used in electronic and electrical systems and equipment. They read electrical wiring plans and tie the wire together according to specifications, using cable ties, cable lacing, electrical conduit, and sleeves.',
  'esco role: legal administrative assistant \n description: Legal administrative assistants carry out the daily administrative activities of firms, offices of notaries, and companies. They perform activities such as writing mails, phone-answering and typing/keyboarding. They combine these activities with specific knowledge and understanding of the procedures and codes managed in legal business affairs.',
  'esco role: cashier \n description: Cashiers operate the cash register, receive payments from customers, issue receipts and return change due.',
  'esco role: tourist information officer \n description: Tourist information officers provide information and advice to travellers about local attractions, events, travelling and accommodation.',
  'esco role: patient transport services driver \n description: Patient transport services drivers transfer disabled, vulnerable and elderly patients to and from health care facilities such as hospitals or social care settings. They drive the ambulance and maintain all the related equipment but under non-emergency circumstances.',
  'esco role: client relations manager \n description: \nClient relations managers act as the middle person between a company and its customers. They ensure that the customers are satisfied by providing them with guidance and explanation on their accounts and services received by the company. They also have possible other tasks such as developing plans or delivering proposals.',