In [1]:
import pandas as pd
import numpy as np

In [2]:
df_new = pd.read_csv('../data/processed/master_datasets_2/master_complete_hierarchy_w_occ.csv')

/tmp/ipykernel_2059866/4272898541.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_new = pd.read_csv('../data/processed/master_datasets_2/master_complete_hierarchy_w_occ.csv')

In [10]:
df_new.query("skillLabel == 'serve food in table service'").iloc[0]

occupationUri            http://data.europa.eu/esco/occupation/1801583e...
relationType                                                      optional
skillType_x                                               skill/competence
skillUri                 http://data.europa.eu/esco/skill/42a6eff0-e9d9...
occupationLabel                             hospitality vocational teacher
iscoGroup                                                             2320
occupationDescription    Hospitality vocational teachers instruct stude...
occupationCode                                                   2320.1.15
skillLabel                                     serve food in table service
skillType_y                                               skill/competence
skillAltLabels           serve food during table service\nserve food th...
reuseLevel                                                 sector-specific
status                                                            released
description              Provide food at the table whilst maintaining h...
definition                                                             NaN
pillar_uri               http://data.europa.eu/esco/skill/335228d2-297d...
pillar_label                                                        skills
parent_uri               http://data.europa.eu/esco/skill/1bb32451-7ca4...
parent_label                                       serving food and drinks
full_path_uris           http://data.europa.eu/esco/skill/335228d2-297d...
full_path_labels         skills | assisting and caring | preparing and ...
level1_uri               http://data.europa.eu/esco/skill/c73521be-c039...
level1_label                                          assisting and caring
level2_uri               http://data.europa.eu/esco/skill/b85711bc-32d6...
level2_label                         preparing and serving food and drinks
level3_uri               http://data.europa.eu/esco/skill/1bb32451-7ca4...
level3_label                                       serving food and drinks
Name: 22807, dtype: object

In [12]:
df_new[df_new['skillAltLabels'].str.contains('Chef', case=False, na=False)].iloc[0]

occupationUri            http://data.europa.eu/esco/occupation/3b1ea27c...
relationType                                                      optional
skillType_x                                                      knowledge
skillUri                 http://data.europa.eu/esco/skill/49f85a99-086c...
occupationLabel                       ICT change and configuration manager
iscoGroup                                                             2519
occupationDescription    ICT change and configuration managers organise...
occupationCode                                                      2519.3
skillLabel               Chef (tools for software configuration managem...
skillType_y                                                      knowledge
skillAltLabels                                                        Chef
reuseLevel                                                 sector-specific
status                                                            released
description              The tool Chef is a software program which perf...
definition                                                             NaN
pillar_uri               http://data.europa.eu/esco/skill/c46fcb45-5c14...
pillar_label                                                     knowledge
parent_uri                         http://data.europa.eu/esco/isced-f/0613
parent_label             software and applications development and anal...
full_path_uris           http://data.europa.eu/esco/skill/c46fcb45-5c14...
full_path_labels         knowledge | information and communication tech...
level1_uri                           http://data.europa.eu/esco/isced-f/06
level1_label             information and communication technologies (icts)
level2_uri                          http://data.europa.eu/esco/isced-f/061
level2_label             information and communication technologies (icts)
level3_uri                         http://data.europa.eu/esco/isced-f/0613
level3_label             software and applications development and anal...
Name: 54275, dtype: object

In [14]:
df_new.query("skillUri == 'http://data.europa.eu/esco/skill/83723a7f-e905-4d6c-82ba-f40ab873883d'").iloc[0]

occupationUri            http://data.europa.eu/esco/occupation/26105840...
relationType                                                      optional
skillType_x                                               skill/competence
skillUri                 http://data.europa.eu/esco/skill/83723a7f-e905...
occupationLabel                                                 park guide
iscoGroup                                                             5113
occupationDescription    Park guides assist visitors, interpret cultura...
occupationCode                                                    5113.1.2
skillLabel               demonstrate intercultural competences in hospi...
skillType_y                                               skill/competence
skillAltLabels           display an understanding of cultural differenc...
reuseLevel                                                 sector-specific
status                                                            released
description              Understand, respect and build constructive and...
definition                                                             NaN
pillar_uri               http://data.europa.eu/esco/skill/335228d2-297d...
pillar_label                                                        skills
parent_uri               http://data.europa.eu/esco/skill/a19c5139-1250...
parent_label                     communicating with colleagues and clients
full_path_uris           http://data.europa.eu/esco/skill/335228d2-297d...
full_path_labels         skills | communication, collaboration and crea...
level1_uri               http://data.europa.eu/esco/skill/dc06de9f-dd3a...
level1_label                   communication, collaboration and creativity
level2_uri               http://data.europa.eu/esco/skill/b76cd1e5-d5e7...
level2_label                                       liaising and networking
level3_uri               http://data.europa.eu/esco/skill/a19c5139-1250...
level3_label                     communicating with colleagues and clients
Name: 35825, dtype: object

In [7]:
df_new.iloc[0]

occupationUri            http://data.europa.eu/esco/occupation/00030d09...
relationType                                                     essential
skillType_x                                                      knowledge
skillUri                 http://data.europa.eu/esco/skill/fed5b267-73fa...
occupationLabel                                         technical director
iscoGroup                                                             2654
occupationDescription    Technical directors realise the artistic visio...
occupationCode                                                    2654.1.7
skillLabel                                              theatre techniques
skillType_y                                                      knowledge
skillAltLabels           theatre technique\ntheatre approaches\ntheatre...
reuseLevel                                                 sector-specific
status                                                            released
description              The techniques that facilitate a successful pr...
definition                                                             NaN
pillar_uri               http://data.europa.eu/esco/skill/c46fcb45-5c14...
pillar_label                                                     knowledge
parent_uri                         http://data.europa.eu/esco/isced-f/0215
parent_label                                     music and performing arts
full_path_uris           http://data.europa.eu/esco/skill/c46fcb45-5c14...
full_path_labels         knowledge | arts and humanities | arts | music...
level1_uri                           http://data.europa.eu/esco/isced-f/02
level1_label                                           arts and humanities
level2_uri                          http://data.europa.eu/esco/isced-f/021
level2_label                                                          arts
level3_uri                         http://data.europa.eu/esco/isced-f/0215
level3_label                                     music and performing arts
Name: 0, dtype: object

In [8]:
df_new[['occupationUri','skillUri','relationType']].drop_duplicates().relationType.value_counts()

relationType
essential    67622
optional     61382
Name: count, dtype: int64

In [10]:
df_new[['occupationUri','skillUri','relationType', 'skillType_x']].drop_duplicates().skillType_x.value_counts()

skillType_x
skill/competence    93636
knowledge           35309
Name: count, dtype: int64

In [12]:
df_new[['occupationUri','skillUri','relationType', 'pillar_label']].drop_duplicates().pillar_label.value_counts()

pillar_label
skills                                95626
knowledge                             35279
transversal skills and competences    32740
language skills and knowledge            30
Name: count, dtype: int64

In [14]:
df_new[['occupationUri','skillUri','relationType', 'reuseLevel']].drop_duplicates().reuseLevel.value_counts()

reuseLevel
cross-sector           72359
sector-specific        52946
occupation-specific     3613
transversal               27
Name: count, dtype: int64

In [4]:
df_h = pd.read_csv('../data/processed/master_datasets_2/master_skill_complete_hierarchy.csv')

FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/master_datasets_2/master_skill_complete_hierarchy.csv'

In [ ]:
df_new.shape

(229540, 27)

In [ ]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229540 entries, 0 to 229539
Data columns (total 27 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   occupationUri          229540 non-null  object
 1   relationType           229540 non-null  object
 2   skillType_x            229481 non-null  object
 3   skillUri               229540 non-null  object
 4   occupationLabel        229540 non-null  object
 5   iscoGroup              229540 non-null  int64
 6   occupationDescription  229540 non-null  object
 7   occupationCode         229540 non-null  object
 8   skillLabel             229540 non-null  object
 9   skillType_y            229481 non-null  object
 10  skillAltLabels         220823 non-null  object
 11  reuseLevel             229481 non-null  object
 12  status                 229540 non-null  object
 13  description            229540 non-null  object
 14  definition             11 non-null      object
 15  pillar_uri             229540 non-null  object
 16  pillar_label           229540 non-null  object
 17  parent_uri             229540 non-null  object
 18  parent_label           229540 non-null  object
 19  full_path_uris         229540 non-null  object
 20  full_path_labels       229540 non-null  object
 21  level1_uri             229540 non-null  object
 22  level1_label           229540 non-null  object
 23  level2_uri             229519 non-null  object
 24  level2_label           229519 non-null  object
 25  level3_uri             229478 non-null  object
 26  level3_label           229478 non-null  object
dtypes: int64(1), object(26)
memory usage: 47.3+ MB

In [ ]:
df_h.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24150 entries, 0 to 24149
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   skillUri          24150 non-null  object
 1   skillLabel        24150 non-null  object
 2   skillType         24145 non-null  object
 3   skillAltLabels    23370 non-null  object
 4   reuseLevel        24145 non-null  object
 5   status            24150 non-null  object
 6   description       24150 non-null  object
 7   definition        3 non-null      object
 8   pillar_uri        24150 non-null  object
 9   pillar_label      24150 non-null  object
 10  parent_uri        24150 non-null  object
 11  parent_label      24150 non-null  object
 12  full_path_uris    24150 non-null  object
 13  full_path_labels  24150 non-null  object
 14  level1_uri        24150 non-null  object
 15  level1_label      24150 non-null  object
 16  level2_uri        24077 non-null  object
 17  level2_label      24077 non-null  object
 18  level3_uri        23621 non-null  object
 19  level3_label      23621 non-null  object
dtypes: object(20)
memory usage: 3.7+ MB

In [ ]:
df_new.query('skillType_x != skillType_y').iloc[0]

occupationUri            http://data.europa.eu/esco/occupation/0464b062...
relationType                                                     essential
skillType_x                                                            NaN
skillUri                 http://data.europa.eu/esco/skill/426ceaba-6867...
occupationLabel                                 ICT security administrator
iscoGroup                                                             2529
occupationDescription    ICT security administrators plan and carry out...
occupationCode                                                      2529.6
skillLabel                                                      ICT safety
skillType_y                                                            NaN
skillAltLabels           ICT protection\ninformation and communication ...
reuseLevel                                                             NaN
status                                                            released
description              Personal protection, data protection, digital ...
definition                                                             NaN
pillar_uri               http://data.europa.eu/esco/skill/335228d2-297d...
pillar_label                                                        skills
parent_uri               http://data.europa.eu/esco/skill/185c56ee-098f...
parent_label                                        protecting ict devices
full_path_uris           http://data.europa.eu/esco/skill/335228d2-297d...
full_path_labels         skills | working with computers | setting up a...
level1_uri               http://data.europa.eu/esco/skill/243eb885-07c7...
level1_label                                        working with computers
level2_uri               http://data.europa.eu/esco/skill/75c1ab73-5b00...
level2_label                    setting up and protecting computer systems
level3_uri               http://data.europa.eu/esco/skill/185c56ee-098f...
level3_label                                        protecting ict devices
Name: 4434, dtype: object

In [ ]:
df_new.columns

Index(['occupationUri', 'relationType', 'skillType_x', 'skillUri',
       'occupationLabel', 'iscoGroup', 'occupationDescription',
       'occupationCode', 'skillLabel', 'skillType_y', 'skillAltLabels',
       'reuseLevel', 'status', 'description', 'definition', 'pillar_uri',
       'pillar_label', 'parent_uri', 'parent_label', 'full_path_uris',
       'full_path_labels', 'level1_uri', 'level1_label', 'level2_uri',
       'level2_label', 'level3_uri', 'level3_label'],
      dtype='object')

In [ ]:
df_new[['skillLabel', 'pillar_uri',
       'pillar_label', 'parent_uri', 'parent_label', 'full_path_uris',
       'full_path_labels', 'level1_uri', 'level1_label', 'level2_uri',
       'level2_label', 'level3_uri', 'level3_label']].drop_duplicates().query(
        "skillLabel == 'Python (computer programming)'"
       ).iloc[0,6]

'knowledge | information and communication technologies (icts) | information and communication technologies (icts) | software and applications development and analysis'

In [ ]:
df_new[['skillLabel', 'pillar_uri',
       'pillar_label', 'parent_uri', 'parent_label', 'full_path_uris',
       'full_path_labels', 'level1_uri', 'level1_label', 'level2_uri',
       'level2_label', 'level3_uri', 'level3_label']].drop_duplicates().query(
        "skillLabel == 'Python (computer programming)'"
       ).iloc[1,6]

'knowledge | information and communication technologies (icts) | information and communication technologies (icts) | software and applications development and analysis | computer programming'

In [1]:
# decorte in different format
import pandas as pd
df = pd.read_csv("/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/decorte_test_pairs.csv")

In [2]:
df.query('raw_title == "Consultant"').iloc[:,:4]

,raw_title,raw_description,esco_title,esco_description
398,Consultant,Led an experience design initiative to underst...,business consultant,"Business consultants analyse the position, str..."
402,Consultant,Conducted market research and prepared a busin...,market research analyst,Market research analysts collect the informati...
405,Consultant,"Projects: ETGIS, Leak Repair, Cathodic Protect...",business analyst,Business analysts research and understand the ...
409,Consultant,Provided analysis and assistance in various ta...,tax advisor,Tax advisors use their expertise in tax legisl...
421,Consultant,Worked as a consultant at a publicly traded di...,ICT consultant,ICT consultants provide advice on how to optim...
425,Consultant,Working as a Functional Consultant in the SAP ...,ICT business analyst,ICT business analysts are in charge of analysi...
432,Consultant,Creating and developing national programming f...,radio producer,Radio producers are responsible for organising...

In [6]:
df_esco = pd.read_csv('../data/processed/master_datasets_2/master_complete_hierarchy_w_occ.csv')

/tmp/ipykernel_1265953/2024523705.py:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_esco = pd.read_csv('../data/processed/master_datasets_2/master_complete_hierarchy_w_occ.csv')

In [7]:
df.merge(df_esco, left_on='esco_id', right_on='occupationUri').raw_title.nunique()

840

In [12]:
df.merge(df_skills_occ, left_on='esco_id', right_on='occupationUri', how='left').raw_title.nunique()

841

In [13]:
df.raw_title.count()

np.int64(926)

In [17]:
df_skills = pd.read_csv(r"/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/esco_datasets/skills_en.csv")

In [18]:
df_skills.iloc[0]

conceptType                                KnowledgeSkillCompetence
conceptUri        http://data.europa.eu/esco/skill/0005c151-5b5a...
skillType                                          skill/competence
reuseLevel                                          sector-specific
preferredLabel                                 manage musical staff
altLabels         manage staff of music\ncoordinate duties of mu...
hiddenLabels                                                    NaN
status                                                     released
modifiedDate                               2023-11-30T15:53:37.136Z
scopeNote                                                       NaN
definition                                                      NaN
inScheme          http://data.europa.eu/esco/concept-scheme/skil...
description       Assign and manage staff tasks in areas such as...
Name: 0, dtype: object

In [10]:
df_skills_occ = pd.read_csv(r"/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/esco_datasets/occupationSkillRelations_en.csv")

In [11]:
df_skills_occ.skillUri.nunique()

13492

In [19]:
df_skills_occ

,occupationUri,relationType,skillType,skillUri
0,http://data.europa.eu/esco/occupation/00030d09...,essential,knowledge,http://data.europa.eu/esco/skill/fed5b267-73fa...
1,http://data.europa.eu/esco/occupation/00030d09...,essential,skill/competence,http://data.europa.eu/esco/skill/05bc7677-5a64...
2,http://data.europa.eu/esco/occupation/00030d09...,essential,skill/competence,http://data.europa.eu/esco/skill/271a36a0-bc7a...
3,http://data.europa.eu/esco/occupation/00030d09...,essential,skill/competence,http://data.europa.eu/esco/skill/47ed1d37-971b...
4,http://data.europa.eu/esco/occupation/00030d09...,essential,skill/competence,http://data.europa.eu/esco/skill/591dd514-735b...
...,...,...,...,...
128999,http://data.europa.eu/esco/occupation/ffc292f1...,optional,skill/competence,http://data.europa.eu/esco/skill/df487cde-38d4...
129000,http://data.europa.eu/esco/occupation/ffc292f1...,optional,skill/competence,http://data.europa.eu/esco/skill/e975b791-b488...
129001,http://data.europa.eu/esco/occupation/ffc292f1...,optional,skill/competence,http://data.europa.eu/esco/skill/ed938748-60ae...
129002,http://data.europa.eu/esco/occupation/ffc292f1...,optional,skill/competence,http://data.europa.eu/esco/skill/f30a7ea4-77dd...
129003,http://data.europa.eu/esco/occupation/ffc292f1...,optional,skill/competence,http://data.europa.eu/esco/skill/fd60bbcc-c3b6...

In [18]:
df_esco.shape

(229540, 27)

In [5]:
df_skills.conceptUri.nunique()

13939

In [8]:
df_skills.preferredLabel.nunique()

13939

In [9]:
df_skills.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13939 entries, 0 to 13938
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   conceptType     13939 non-null  object
 1   conceptUri      13939 non-null  object
 2   skillType       13934 non-null  object
 3   reuseLevel      13934 non-null  object
 4   preferredLabel  13939 non-null  object
 5   altLabels       13591 non-null  object
 6   hiddenLabels    153 non-null    object
 7   status          13939 non-null  object
 8   modifiedDate    13939 non-null  object
 9   scopeNote       234 non-null    object
 10  definition      3 non-null      object
 11  inScheme        13939 non-null  object
 12  description     13939 non-null  object
dtypes: object(13)
memory usage: 1.4+ MB

In [13]:
df_esco.skillUri.nunique()

13492

In [12]:
res = pd.read_csv(r"/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/results/master_results_new.csv", sep=',', quoting=1)

## Results

In [16]:
import pandas as pd
import numpy as np


df_res = pd.read_csv(r"/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/results/master_results_new.csv", sep=',', quoting=1)

In [14]:
df_res.iloc[1]

MAP@10                                                            0.133645
MAP@20                                                            0.097923
MAP@5                                                             0.172868
MAP@50                                                            0.070449
MAP@full                                                          0.104225
P@10                                                              0.226703
P@20                                                              0.194541
P@5                                                               0.248865
P@50                                                              0.148022
P@full                                                            0.000571
R@10                                                              0.049492
R@20                                                              0.083711
R@5                                                                0.02727
R@50                                                              0.154659
R@full                                                                 1.0
base_encoder_ckpt                                         all-MiniLM-L6-v2
batch_size                                                              32
cat_model_ckpt                                                         NaN
cat_threshold                                                          0.1
corpus_size                                                          96617
device                                                                cuda
duration_seconds                                                     507.6
esco_data_path           data/processed/master_datasets_2/master_comple...
hidden_dim                                                             NaN
hier_level                                                             NaN
is_structured                                                        False
job_data_path            /dss/dsshome1/02/ra95kix2/thesis/skills4cpp/da...
num_queries_evaluated                                                  925
out_dir                                                           results/
process                                                           BASELINE
run_name                                                               NaN
seed                                                                    42
skill_encoder_ckpt                                     TechWolf/JobBERT-v2
text_fields                                                          title
timestamp                                 2025-11-12T17:01:21.303602+00:00
top_k                                                                96617
use_expanded_corpus                                                   True
Name: 1, dtype: object

In [7]:
df_res.iloc[1]

MAP@10                                                            0.133645
MAP@20                                                            0.097923
MAP@5                                                             0.172868
MAP@50                                                            0.070449
MAP@full                                                          0.104225
P@10                                                              0.226703
P@20                                                              0.194541
P@5                                                               0.248865
P@50                                                              0.148022
P@full                                                            0.000571
R@10                                                              0.049492
R@20                                                              0.083711
R@5                                                                0.02727
R@50                                                              0.154659
R@full                                                                 1.0
base_encoder_ckpt                                         all-MiniLM-L6-v2
batch_size                                                              32
cat_model_ckpt                                                         NaN
cat_threshold                                                          0.1
corpus_size                                                          96617
device                                                                cuda
duration_seconds                                                     507.6
esco_data_path           data/processed/master_datasets_2/master_comple...
hidden_dim                                                             NaN
hier_level                                                             NaN
is_structured                                                        False
job_data_path            /dss/dsshome1/02/ra95kix2/thesis/skills4cpp/da...
num_queries_evaluated                                                  925
out_dir                                                           results/
process                                                           BASELINE
run_name                                                               NaN
seed                                                                    42
skill_encoder_ckpt                                     TechWolf/JobBERT-v2
text_fields                                                          title
timestamp                                 2025-11-12T17:01:21.303602+00:00
top_k                                                                96617
use_expanded_corpus                                                   True
Name: 1, dtype: object

In [9]:
df_res.loc[1, 'job_data_path']

'/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/decorte_test_pairs.csv'

In [10]:
df_res.iloc[-2]

MAP@10                                                            0.148301
MAP@20                                                            0.109959
MAP@5                                                             0.195524
MAP@50                                                            0.077081
MAP@full                                                          0.064874
P@10                                                              0.241622
P@20                                                              0.209081
P@5                                                                  0.272
P@50                                                              0.155719
P@full                                                            0.000577
R@10                                                              0.052234
R@20                                                              0.088197
R@5                                                               0.029825
R@50                                                              0.161506
R@full                                                            0.161506
base_encoder_ckpt                                         all-MiniLM-L6-v2
batch_size                                                              32
cat_model_ckpt                                                         NaN
cat_threshold                                                          0.1
corpus_size                                                          13492
device                                                                cuda
duration_seconds                                                     19.25
esco_data_path           data/processed/master_datasets_2/master_comple...
hidden_dim                                                             NaN
hier_level                                                             NaN
is_structured                                                        False
job_data_path                 data/title_pairs_desc/decorte_test_pairs.csv
num_queries_evaluated                                                  925
out_dir                                                           results/
process                                                           BASELINE
run_name                                             eval_baseline_JobBERT
seed                                                                    42
skill_encoder_ckpt                                     TechWolf/JobBERT-v2
text_fields                                                          title
timestamp                                 2025-11-14T02:59:00.723399+00:00
top_k                                                                   50
use_expanded_corpus                                                  False
Name: 2, dtype: object

In [19]:
df_res

,MAP@10,MAP@20,MAP@5,MAP@50,MAP@full,P@10,P@20,P@5,P@50,P@full,...,num_queries_evaluated,out_dir,process,run_name,seed,skill_encoder_ckpt,text_fields,timestamp,top_k,use_expanded_corpus
0,0.133645,0.092925,0.172868,0.047336,0.040894,0.226703,0.182378,0.248865,0.078854,0.000041,...,925,results/,BASELINE,NaN,42,TechWolf/JobBERT-v2,title,2025-11-12T16:50:36.553228+00:00,50,True
1,0.133645,0.097923,0.172868,0.070449,0.104225,0.226703,0.194541,0.248865,0.148022,0.000571,...,925,results/,BASELINE,NaN,42,TechWolf/JobBERT-v2,title,2025-11-12T17:01:21.303602+00:00,96617,True
2,0.148301,0.109959,0.195524,0.077081,0.064874,0.241622,0.209081,0.272000,0.155719,0.000577,...,925,results/,BASELINE,eval_baseline_JobBERT,42,TechWolf/JobBERT-v2,title,2025-11-14T02:59:00.723399+00:00,50,False
3,0.148301,0.109959,0.195524,0.077081,0.064874,0.241622,0.209081,0.272000,0.155719,0.000577,...,925,results/,BASELINE,eval_baseline_JobBERT,42,TechWolf/JobBERT-v2,title,2025-11-14T14:24:18.733926+00:00,50,False
4,0.133645,0.092925,0.172868,0.047336,0.040894,0.226703,0.182378,0.248865,0.078854,0.000041,...,925,results/,BASELINE,eval_baseline_JobBERT,42,TechWolf/JobBERT-v2,title,2025-11-14T14:42:01.453460+00:00,50,True
5,0.133645,0.092925,0.172868,0.047336,0.040894,0.226703,0.182378,0.248865,0.078854,0.000041,...,925,results/,BASELINE,eval_baseline_JobBERT,42,TechWolf/JobBERT-v2,title,2025-11-14T14:53:17.941969+00:00,50,True
6,0.133645,0.092925,0.172868,0.047336,0.040894,0.226703,0.182378,0.248865,0.078854,0.000041,...,925,results/,BASELINE,eval_baseline_jobbert,42,TechWolf/JobBERT-v2,title,2025-11-14T15:14:02.228180+00:00,50,True
7,0.115090,0.085865,0.150418,0.044011,0.038035,0.206486,0.182054,0.224865,0.078854,0.000041,...,925,results/,HYBRID,eval_hybrid_L1,42,TechWolf/JobBERT-v2,title,2025-11-14T15:42:48.035422+00:00,50,True
8,0.148301,0.109959,0.195524,0.077081,0.064874,0.241622,0.209081,0.272000,0.155719,0.000577,...,925,results/,BASELINE,eval_baseline_JobBERT_k50,42,TechWolf/JobBERT-v2,title,2025-11-14T15:44:45.890875+00:00,50,False
9,0.133645,0.092925,0.172868,0.047336,0.040894,0.226703,0.182378,0.248865,0.078854,0.000041,...,925,results/,BASELINE,eval_baseline_JobBERT_k50,42,TechWolf/JobBERT-v2,title,2025-11-14T15:45:44.692639+00:00,50,True
10,0.121180,0.088369,0.166930,0.068726,0.057640,0.208865,0.182054,0.239135,0.155719,0.000577,...,925,results/,HYBRID,eval_hybrid_L1_k50,42,TechWolf/JobBERT-v2,title,2025-11-14T15:46:48.054511+00:00,50,False
11,0.115090,0.085865,0.150418,0.044011,0.038035,0.206486,0.182054,0.224865,0.078854,0.000041,...,925,results/,HYBRID,eval_hybrid_L1_k50,42,TechWolf/JobBERT-v2,title,2025-11-14T15:49:31.443046+00:00,50,True
12,0.122564,0.088538,0.157405,0.045546,0.039550,0.215135,0.181405,0.231351,0.078854,0.000041,...,925,results/,HYBRID,eval_hybrid_L2_k50,42,TechWolf/JobBERT-v2,title,2025-11-14T15:57:03.158501+00:00,50,True
13,0.134642,0.098443,0.176270,0.072594,0.061097,0.228432,0.196216,0.251027,0.155741,0.000577,...,925,results/,HYBRID,eval_hybrid_L2_k50,42,TechWolf/JobBERT-v2,title,2025-11-14T15:57:35.855421+00:00,50,False
14,0.139884,0.102591,0.182879,0.074142,0.062286,0.231784,0.200486,0.255568,0.155741,0.000578,...,925,results/,HYBRID,eval_hybrid_L3_k50,42,TechWolf/JobBERT-v2,title,2025-11-14T16:00:41.669933+00:00,50,False
15,0.125070,0.090118,0.164753,0.045933,0.039612,0.217514,0.182757,0.240216,0.078854,0.000041,...,925,results/,HYBRID,eval_hybrid_L3_k50,42,TechWolf/JobBERT-v2,title,2025-11-14T16:01:42.402446+00:00,50,True

In [20]:
dec_test = pd.read_csv(r"/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/data/title_pairs_desc/decorte_test_pairs.csv")

In [21]:
dec_test.iloc[0]

raw_title                                             Chef de Cuisine
raw_description     Worked with executive chef to develop and exec...
esco_title                                                  head chef
esco_description    Head chefs manage the kitchen to oversee the p...
esco_id             http://data.europa.eu/esco/occupation/01484951...
Name: 0, dtype: object

In [22]:
dec_test.head()

,raw_title,raw_description,esco_title,esco_description,esco_id
0,Chef de Cuisine,Worked with executive chef to develop and exec...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...
1,Chef/General Manager,Developed food and beverage menu for a new fas...,restaurant manager,Restaurant managers are in charge of managing ...,http://data.europa.eu/esco/occupation/d5eb6150...
2,Executive Chef,Co-ordinated and executed meals for various co...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...
3,"Lead Cook/Kitchen Trainer, Kitchen Manager",- Cook and Prepare meals for our guest.\n- Res...,cook,Cooks are culinary operatives who are able to ...,http://data.europa.eu/esco/occupation/90f75f67...
4,Lead Cook,- Put in product orders for the Restaurant.\n-...,head chef,Head chefs manage the kitchen to oversee the p...,http://data.europa.eu/esco/occupation/01484951...

# esco decorte master skills

In [8]:
import json
import pandas as pd

# Load the JSON file and convert to DataFrame
with open('/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/results/decorte_jobbert_v2_baseline/job_title_skills_master.json', 'r') as f:
    data = json.load(f)

# Convert to DataFrame
df_master_skills = pd.DataFrame(data)

In [9]:
# Expand the skills column into multiple rows
df_master_skills_expanded = df_master_skills.explode('skills').reset_index()

# Extract skill information into separate columns
df_master_skills_expanded['skill'] = df_master_skills_expanded['skills'].apply(lambda x: x['skill'] if isinstance(x, dict) else None)
df_master_skills_expanded['score'] = df_master_skills_expanded['skills'].apply(lambda x: x['score'] if isinstance(x, dict) else None)
df_master_skills_expanded['skillUri'] = df_master_skills_expanded['skills'].apply(lambda x: x['skillUri'] if isinstance(x, dict) else None)

# Drop the original skills column
df_master_skills_expanded = df_master_skills_expanded.drop('skills', axis=1)

# Rename the index column to track original rows
df_master_skills_expanded = df_master_skills_expanded.rename(columns={'index': 'original_row_index'})

df_master_skills_expanded.head()

,original_row_index,job_title,skill,score,skillUri
0,0,Line Cook,compile cooking recipes,0.646475,http://data.europa.eu/esco/skill/f4a30153-2b27...
1,0,Line Cook,food canning production line,0.637590,http://data.europa.eu/esco/skill/27b86b4c-758e...
2,0,Line Cook,prepare garnish for drinks,0.629284,http://data.europa.eu/esco/skill/80ec44cc-372a...
3,0,Line Cook,cook meat dishes,0.626296,http://data.europa.eu/esco/skill/f19f0cda-73f4...
4,0,Line Cook,assemble cocktail garnishes,0.615691,http://data.europa.eu/esco/skill/f42df0af-c63b...

In [10]:
df_master_skills_expanded.groupby('job_title').original_row_index.nunique().sort_values()

job_title
Owner - Graphic Artist                    1
Owner, Operator                           1
Owner, Manager                            1
Owner, Executive Chef General Manager     1
Owner and Operator                        1
                                         ..
Teacher                                  24
Sales Associate                          28
Manager                                  34
Intern                                   43
Consultant                               49
Name: original_row_index, Length: 6309, dtype: int64

In [11]:
df_master_skills_expanded.query("job_title == 'Intern' and skill == 'conduct field work'")

,original_row_index,job_title,skill,score,skillUri
11050,221,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
15650,313,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
17600,352,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
23050,461,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
24800,496,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
26500,530,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
33950,679,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
43800,876,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
45450,909,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
45550,911,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
48750,975,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
53250,1065,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
57950,1159,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
68450,1369,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
68500,1370,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
70750,1415,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
74050,1481,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
78400,1568,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
83250,1665,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
85300,1706,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
89850,1797,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
89900,1798,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
91850,1837,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
99250,1985,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
106400,2128,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
106450,2129,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
108150,2163,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
131550,2631,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
207650,4153,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
217100,4342,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
264150,5283,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
291000,5820,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
310300,6206,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
310500,6210,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
310550,6211,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
320600,6412,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
322650,6453,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
351000,7020,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
351600,7032,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
353100,7062,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
358000,7160,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
385800,7716,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...
396150,7923,Intern,conduct field work,0.529448,http://data.europa.eu/esco/skill/bc54eee1-a858...

In [13]:
df_master_skills_expanded = df_master_skills_expanded.drop_duplicates(subset=['job_title', 'skillUri'])

In [16]:
df_master_skills_expanded.to_csv('/dss/dsshome1/02/ra95kix2/thesis/skills4cpp/results/decorte_jobbert_v2_baseline/job_title_skills_master.csv', index=False)

In [25]:
df_master_skills_expanded.skill.nunique()

12397

In [8]:
df_master_skills_expanded.groupby('job_title').skill.nunique().sort_values()

job_title
1st and 2nd Grade Sunday School Teacher                         50
21st Century Site Coordinator                                   50
25Live Functional Administrator/Supervisor of I.T. Help Desk    50
2nd Grade Replacement Teacher                                   50
2nd Grade Teacher                                               50
                                                                ..
Youth Program Assistant                                         50
Youth Worker                                                    50
Youth leader                                                    50
Zonal Manager (Corporate Sales)                                 50
dfyaerh                                                         50
Name: skill, Length: 6309, dtype: int64

In [28]:
df_new.columns

Index(['occupationUri', 'relationType', 'skillType_x', 'skillUri',
       'occupationLabel', 'iscoGroup', 'occupationDescription',
       'occupationCode', 'skillLabel', 'skillType_y', 'skillAltLabels',
       'reuseLevel', 'status', 'description', 'definition', 'pillar_uri',
       'pillar_label', 'parent_uri', 'parent_label', 'full_path_uris',
       'full_path_labels', 'level1_uri', 'level1_label', 'level2_uri',
       'level2_label', 'level3_uri', 'level3_label'],
      dtype='object')

In [29]:
df_new.iloc[0]

occupationUri            http://data.europa.eu/esco/occupation/00030d09...
relationType                                                     essential
skillType_x                                                      knowledge
skillUri                 http://data.europa.eu/esco/skill/fed5b267-73fa...
occupationLabel                                         technical director
iscoGroup                                                             2654
occupationDescription    Technical directors realise the artistic visio...
occupationCode                                                    2654.1.7
skillLabel                                              theatre techniques
skillType_y                                                      knowledge
skillAltLabels           theatre technique\ntheatre approaches\ntheatre...
reuseLevel                                                 sector-specific
status                                                            released
description              The techniques that facilitate a successful pr...
definition                                                             NaN
pillar_uri               http://data.europa.eu/esco/skill/c46fcb45-5c14...
pillar_label                                                     knowledge
parent_uri                         http://data.europa.eu/esco/isced-f/0215
parent_label                                     music and performing arts
full_path_uris           http://data.europa.eu/esco/skill/c46fcb45-5c14...
full_path_labels         knowledge | arts and humanities | arts | music...
level1_uri                           http://data.europa.eu/esco/isced-f/02
level1_label                                           arts and humanities
level2_uri                          http://data.europa.eu/esco/isced-f/021
level2_label                                                          arts
level3_uri                         http://data.europa.eu/esco/isced-f/0215
level3_label                                     music and performing arts
Name: 0, dtype: object

In [31]:
df_new[['occupationUri', 'occupationLabel', 'skillUri', 'skillLabel']].drop_duplicates().groupby('skillLabel').occupationLabel.nunique().sort_values()

skillLabel
coordinate the activities of chimney sweeps                   1
coordinate the procurement of organs for transplantation      1
coordinate the running of a performance                       1
coordinate the sale of game                                   1
provide information on mortuary services                      1
                                                           ...
keep records of work progress                               323
manage budgets                                              323
manage staff                                                337
use different communication channels                        342
create solutions to problems                                347
Name: occupationLabel, Length: 13492, dtype: int64

In [32]:
df_new.level1_label.unique()

array(['arts and humanities', 'management skills', 'information skills',
       'communication, collaboration and creativity',
       'self-management skills and competences',
       'social and communication skills and competences',
       'engineering, manufacturing and construction',
       'business, administration and law', 'constructing',
       'handling and moving',
       'working with machinery and specialised equipment',
       'working with computers', 'thinking skills and competences',
       'assisting and caring', 'life skills and competences', 'services',
       'information and communication technologies (icts)',
       'natural sciences, mathematics and statistics',
       'physical and manual skills and competences',
       'core skills and competences', 'health and welfare',
       'agriculture, forestry, fisheries and veterinary', 'education',
       'generic programmes and qualifications',
       'social sciences, journalism and information',
       'classical languages', 'languages'], dtype=object)

In [34]:
df_new.level1_label.nunique()

27

In [35]:
df_new.level2_label.nunique()

136

In [9]:
df_skill_h = pd.read_csv('../data/processed/master_datasets_2/master_skill_complete_hierarchy.csv')

In [14]:
df_skill_h.query("skillLabel == 'manage musical staff'").full_path_labels.unique()

array(['skills | management skills | supervising people | supervising a team or group',
       'transversal skills and competences | social and communication skills and competences | leading others | lead others',
       'skills | management skills | supervising people | supervising a team or group | manage staff',
       'transversal skills and competences | social and communication skills and competences | leading others | lead others | manage staff',
       'skills | management skills | organising, planning and scheduling work and activities | directing operational activities | manage facilities services | manage staff',
       'transversal skills and competences | social and communication skills and competences | leading others | lead others | manage facilities services | manage staff'],
      dtype=object)

In [40]:
df_master_skills_expanded.columns

Index(['original_row_index', 'job_title', 'skill', 'score', 'skillUri'], dtype='object')

In [17]:
df_skill_h.iloc[0]

skillUri            http://data.europa.eu/esco/skill/0005c151-5b5a...
skillLabel                                       manage musical staff
skillType                                            skill/competence
skillAltLabels      manage staff of music\ncoordinate duties of mu...
reuseLevel                                            sector-specific
status                                                       released
description         Assign and manage staff tasks in areas such as...
definition                                                        NaN
pillar_uri          http://data.europa.eu/esco/skill/335228d2-297d...
pillar_label                                                   skills
parent_uri          http://data.europa.eu/esco/skill/aab9f44d-fe0e...
parent_label                              supervising a team or group
full_path_uris      http://data.europa.eu/esco/skill/335228d2-297d...
full_path_labels    skills | management skills | supervising peopl...
level1_uri          http://data.europa.eu/esco/skill/869fc2ce-478f...
level1_label                                        management skills
level2_uri          http://data.europa.eu/esco/skill/7a00c77c-4a1c...
level2_label                                       supervising people
level3_uri          http://data.europa.eu/esco/skill/aab9f44d-fe0e...
level3_label                              supervising a team or group
Name: 0, dtype: object

In [43]:
df_skill_h.groupby('skillUri').skillType.nunique().sort_values().reset_index().groupby('skillType').skillUri.nunique()

skillType
0        5
1    13934
Name: skillUri, dtype: int64

In [51]:
df_skill_h.groupby('skillType').pillar_label.value_counts()

skillType         pillar_label
knowledge         knowledge                              3842
                  skills                                  222
                  transversal skills and competences      172
                  language skills and knowledge            77
skill/competence  skills                                15877
                  transversal skills and competences     3658
                  language skills and knowledge           285
                  knowledge                                12
Name: count, dtype: int64

In [46]:
df_skill_h.pillar_label.value_counts()

pillar_label
skills                                16104
knowledge                              3854
transversal skills and competences     3830
language skills and knowledge           362
Name: count, dtype: int64

In [41]:
df_skill_h.groupby('skillUri').reuseLevel.nunique().sort_values().reset_index().groupby('reuseLevel').skillUri.nunique()

reuseLevel
0        5
1    13934
Name: skillUri, dtype: int64

In [42]:
df_skill_h.groupby('skillUri').pillar_label.nunique().sort_values().reset_index().groupby('pillar_label').skillUri.nunique()

pillar_label
1    10983
2     2925
3       31
Name: skillUri, dtype: int64

In [27]:
df_skill_h.groupby('skillUri').level1_label.nunique().sort_values().reset_index().groupby('level1_label').skillUri.nunique()

level1_label
1    10086
2     2881
3      687
4      192
5       59
6       31
7        3
Name: skillUri, dtype: int64

In [33]:
df_skill_h.pivot_table(
    index='skillUri',
    columns='level1_label',
    values='skillLabel',
    aggfunc='nunique'
).fillna(0).reset_index()

level1_label,skillUri,"agriculture, forestry, fisheries and veterinary",arts and humanities,assisting and caring,"business, administration and law",classical languages,"communication, collaboration and creativity",constructing,core skills and competences,education,...,management skills,"natural sciences, mathematics and statistics",physical and manual skills and competences,self-management skills and competences,services,social and communication skills and competences,"social sciences, journalism and information",thinking skills and competences,working with computers,working with machinery and specialised equipment
0,http://data.europa.eu/esco/skill/0005c151-5b5a...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,http://data.europa.eu/esco/skill/00064735-8fad...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,http://data.europa.eu/esco/skill/000709ed-2be5...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,http://data.europa.eu/esco/skill/0007bdc2-dd15...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,http://data.europa.eu/esco/skill/00090cc1-1f27...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13934,http://data.europa.eu/esco/skill/ffef5eb3-a15e...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13935,http://data.europa.eu/esco/skill/fff0b074-5a76...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13936,http://data.europa.eu/esco/skill/fff0e2cd-d0bd...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13937,http://data.europa.eu/esco/skill/fff5bc45-b506...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
13938,http://data.europa.eu/esco/skill/fff74a70-4f82...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
df_skill_h.pivot_table(
    index='skillUri',
    columns='pillar_label',
    values='skillLabel',
    aggfunc='nunique'
).fillna(0).reset_index()

pillar_label,skillUri,knowledge,language skills and knowledge,skills,transversal skills and competences
0,http://data.europa.eu/esco/skill/0005c151-5b5a...,0.0,0.0,1.0,1.0
1,http://data.europa.eu/esco/skill/00064735-8fad...,0.0,0.0,1.0,0.0
2,http://data.europa.eu/esco/skill/000709ed-2be5...,0.0,0.0,1.0,0.0
3,http://data.europa.eu/esco/skill/0007bdc2-dd15...,0.0,0.0,1.0,0.0
4,http://data.europa.eu/esco/skill/00090cc1-1f27...,0.0,0.0,1.0,0.0
...,...,...,...,...,...
13934,http://data.europa.eu/esco/skill/ffef5eb3-a15e...,0.0,0.0,1.0,0.0
13935,http://data.europa.eu/esco/skill/fff0b074-5a76...,0.0,0.0,1.0,0.0
13936,http://data.europa.eu/esco/skill/fff0e2cd-d0bd...,1.0,0.0,0.0,0.0
13937,http://data.europa.eu/esco/skill/fff5bc45-b506...,0.0,0.0,1.0,1.0
13938,http://data.europa.eu/esco/skill/fff74a70-4f82...,0.0,0.0,1.0,0.0

In [50]:
df_skill_h.columns

Index(['skillUri', 'skillLabel', 'skillType', 'skillAltLabels', 'reuseLevel',
       'status', 'description', 'definition', 'pillar_uri', 'pillar_label',
       'parent_uri', 'parent_label', 'full_path_uris', 'full_path_labels',
       'level1_uri', 'level1_label', 'level2_uri', 'level2_label',
       'level3_uri', 'level3_label'],
      dtype='object')

In [ ]:
# Keep only columns you care about
esco_meta_cols = ["skillUri", "type", "reuseLevel", "pillar_label", "level1_label"]
esco_meta = df_skill_h[esco_meta_cols].copy()

# Merge; this will naturally handle multi-parent skills by giving multiple rows
master = df_master_skills_expanded.merge(esco_meta, on="skillUri", how="left")

KeyError: "['type', 'pillar', 'level1'] not in index"

In [1]:
df_master_skills_expanded.head()

NameError: name 'df_master_skills_expanded' is not defined